### ISSUE TITLE
ImportError: No module named 'requests.packages'

### ISSUE THREAD

**Issue by musicformellons** [kennethreitz/pipenv#366] opened 2017-05-18 19:57 UTC
I have a working ansible script on ubuntu 16.04:
  - name: create a virtualenv with pipenv and python 3
    command: pipenv install {{item}} --three chdir={{ virtualenv_dir }}  
    with_items:
      - argparse==1.2.1
      - boto==2.33.0
      - future==0.15.2

However now I have to adjust it to ubuntu 14.04 (and using python 2 in the virtual environment):
  - name: create a virtualenv with pipenv and python 2
    command: pipenv install {{item}} --two chdir={{ virtualenv_dir }} 
    with_items:
      - argparse==1.2.1
      - boto==2.33.0
      - future==0.15.2

For each package I get the error:

`failed: [92.222.10.96] (item=argparse==1.2.1) => {"changed": true, "cmd": ["pipenv", "install", "argparse==1.2.1", "--two", "state=present"], "delta": "0:00:00.402764", "end": "2017-05-18 21:47:04.291328", "failed": true, "item": "argparse==1.2.1", "rc": 1, "start": "2017-05-18 21:47:03.888564", "stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/pipenv\", line 7, in <module>\n    from pipenv import cli\n  File \"/usr/local/lib/python3.4/dist-packages/pipenv/__init__.py\", line 14, in <module>\n    from .cli import cli\n  File \"/usr/local/lib/python3.4/dist-packages/pipenv/cli.py\", line 21, in <module>\n    from requests.packages.urllib3.exceptions import InsecureRequestWarning\nImportError: No module named 'requests.packages'", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/local/bin/pipenv\", line 7, in <module>", "    from pipenv import cli", "  File \"/usr/local/lib/python3.4/dist-packages/pipenv/__init__.py\", line 14, in <module>", "    from .cli import cli", "  File \"/usr/local/lib/python3.4/dist-packages/pipenv/cli.py\", line 21, in <module>", "    from requests.packages.urllib3.exceptions import InsecureRequestWarning", "ImportError: No module named 'requests.packages'"], "stdout": "", "stdout_lines": []}`

So something is wrong with requests package it seems. But when I check the requests package is installed (both for python 2 and for python 3), so I do not quite get why it 'is missing'.

BTW, I also ssh'ed into the server and tried to manually install some packages with pipenv but got similar errormessage:
```
/home/usr/env# pipenv install argparse==1.2.1
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/usr/local/lib/python3.4/dist-packages/pipenv/__init__.py", line 14, in <module>
    from .cli import cli
  File "/usr/local/lib/python3.4/dist-packages/pipenv/cli.py", line 21, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: No module named 'requests.packages'
```

UPDATE: I noticed when ssh'ed into the server it gives this error-message for all pipenv commands: 'pipenv shell' etc. I then installed pew and pipenv with pipsi and then I can install packages into the virtualenv, but when subsequently trying to run ansible I get exact same errors again.

**Comment by nateprewitt** [comment] 2017-05-19 13:59
Hey @musicformellons, this should now be resolved in #367. Thanks for brining this to our attention.

**Closed by nateprewitt** 2017-05-19 13:59 UTC

**Comment by musicformellons** [comment] 2017-05-19 20:17
Cool, I will try later this week!

**Comment by musicformellons** [comment] 2017-05-22 14:03
Uh.., what is (best) way to install the master branch...? I probably have to uninstall the pipsi install I currently have?

**Comment by nateprewitt** [comment] 2017-05-22 16:58
@musicformellons, the easiest way is to do this is to clone the git repository and use setup.py to install `Pipenv`. It's probably not a bad idea to uninstall what you're currently using with pipsi just to be sure you're using the Pipenv version you're expecting.

**Comment by musicformellons** [comment] 2017-05-23 21:10
I try to install the master branch using ansible on an ubuntu 14.04 server with:
```
  - name: clone pipenv
    git:
      repo: 'https://github.com/kennethreitz/pipenv.git'
      dest: /temp/pipenv
      version: master

  - name: install pipenv via repo setup.py (due to issue which I reported)
    command: python2 setup.py install chdir=/temp/pipenv
```
However the mentioned fix is not there and when I check the version of pipenv it is still 4.0.1  

Why do I not get the master branch installed?

**Comment by nateprewitt** [comment] 2017-05-23 21:18
@musicformellons, are you installing pipenv somewhere else in your ansible script? `pipenv` shouldn't be installed by default onto Ubuntu 14.04, so it's getting installed some other way. If this isn't a new instance, I'd log in and use pip to verify `pipenv` is uninstalled. I'd also verify that the project you're running pipenv in is using python2.

**Comment by nateprewitt** [comment] 2017-05-23 21:21
@musicformellons, apologies, I was thinking we'd already released 4.0.2. 4.0.1 is the version number you should have on your new install. Have you verified that 8d98a751 isn't in /temp/pipenv?

**Comment by musicformellons** [comment] 2017-05-23 21:40
@nateprewitt So installing master is currently equal to version 4.0.1, is that correct? I indeed have version 4.0.1 and https://github.com/kennethreitz/pipenv/commit/8d98a751a4edd09f3df8661e750981cc397d3811
 is not included.

When I manually change the code it works as it should. Could the bugfix be included into master?

**Comment by nateprewitt** [comment] 2017-05-23 21:46
Well that's good to hear that the fix is working. So we've released 4.0.1 which is what `pip` will install and master currently *says* it's at 4.0.1, despite being different code, because we haven't done a new release to bump the version number.

If you look at the current [commit log](https://github.com/kennethreitz/pipenv/commits/master) on master, you'll see that 8d98a75 is included there. That means it should be included in your clone. If it's not, something else is going on with your setup.

Since you've confirmed the change works when manually adding it to your setup though, I don't know if there's any further need to debug. That commit will be included in the next release (like 4.0.2).

**Comment by musicformellons** [comment] 2017-05-23 21:51
Mmmh, ok, then probably the ansible play is not correct. Thanks!

**Comment by musicformellons** [comment] 2017-05-24 06:34
The above ansible play does download the correct (master) branch as I can find the updated __init__.py file in it. So it is still odd why running `python setup.py install` gives the incorrect install? Any idea?

**Comment by musicformellons** [comment] 2017-05-24 08:52
To be more clear: It is not like when I ssh into the server and run 'python setup.py install' that it does install the master branch. I only get it working (after installation) by editing the `__init__.py` file by hand. 

So do you know how to get the master branch installed? If not..., when is ETA of 4.0.2 ?

**Comment by nateprewitt** [comment] 2017-05-24 14:01
@musicformellons what commit is HEAD pointing to?
