### ISSUE TITLE
Editable requirements seem to only be installed properly when using --sequential

### ISSUE THREAD

**Issue by philfreo** [kennethreitz/pipenv#777] opened 2017-09-29 21:22 UTC
My project is working fine with Pipfile/pipenv. But only if I install using `pipenv install --sequential`. 

If I then run `pipenv install` without that flag, the command _succeeds_. However subsequently trying to use one of the editable (`-e`) packages causes an ImportError.

I can replicate the following flow:

1. `pipenv install --sequential` -> succeeds
2. `pipenv run ./manage.py db upgrade` -> succeeds
3. `pipenv install` -> succeeds!!!
4. `pipenv run ./manage.py db upgrade` -> FAILS with ImportError referencing one of the `-e` packages.
5. (steps 1-4 can repeat forever)

**Comment by kennethreitz** [comment] 2017-09-29 21:57
please give us an example of your pipfile

**Comment by erinxocon** [comment] 2017-09-30 01:45
Yes, please provide your `Pipfile` if possible for testing.  I'm not able to reproduce currently.

**Comment by kennethreitz** [comment] 2017-09-30 12:14
agreed, cannot reproduce. We'll need to see your `Pipfile`. Closing until then.

**Closed by kennethreitz** 2017-09-30 12:14 UTC
