### ISSUE TITLE
Mysterious Packages Added to lockfile

### ISSUE THREAD

**Issue by cancan101** [kennethreitz/pipenv#1042] opened 2017-11-08 06:50 UTC
Packages are added to lockfile that are not dependencies or listed top level in pipfile.

##### Describe your environment

1. OS Type
`MacOS`
1. Python version: `$ python -V`
`Python 3.5.3`
1. Pipenv version: `$ pipenv --version`
`pipenv, version 8.3.1`
##### Expected result

A lock file that is just the pinned deps of the packages in the pipfile.

##### Actual result

In the lock file, I see:
```
        "medpy": {
            "editable": true,
            "git": "https://github.com/loli/medpy.git",
            "ref": "93885e2de903b1b8ee58c8440023a2ca888ba8e5"
        },
```
`graph` shows this as top level req:
```
```MedPy==0.3.0
  - nibabel [required: >=1.3.0, installed: 2.1.0]
  - numpy [required: >=1.6.1, installed: 1.13.1]
  - pydicom [required: >=0.9.7, installed: 1.0.0a1]
  - scipy [required: >=0.9.0, installed: 0.19.1]
    - numpy [required: >=1.8.2, installed: 1.13.1]```
```
and running `pipenv lock --verbose` prints no info about where it comes from.

##### Steps to replicate
I do have that installed in my env, but not through pipenv:
```
$ pip freeze | grep medp
-e git+https://github.com/loli/medpy.git@93885e2de903b1b8ee58c8440023a2ca888ba8e5#egg=MedPy
```

**Comment by techalchemy** [comment] 2017-11-08 06:53
@cancan101 can you provide your pipfile?

**Comment by cancan101** [comment] 2017-11-08 06:58
I did have to remove two entries as they contained private GH keys, but they should not be touching medpy:
```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

attrs = "*"
click = "*"
imageio = "*"
matplotlib = "*"
nibabel = "*"
nilearn = "*"
numpy = "*"
opencv-python = "==3.3.0.9"
pandas = "*"
pillow = "*"
pynrrd = "*"
scikit-image = "*"
scipy = "*"
tensorflow = { version = "*", markers = "'linux' not in sys_platform" }
tqdm = "*"
object_detection = {git = "https://github.com/cancan101/models.git", subdirectory = "research", ref = "working", editable = true}


[dev-packages]

awscli = "*"
boto = "*"
cython = "*"
"dicom2nifti" = "*"
"flake8" = "*"
"flake8-config-4catalyzer" = "*"
"flake8-import-order" = "<=0.14.99"
"flake8-junit-report" = "*"
"h5py" = "*"
ipykernel = "*"
ipython = "*"
ipywidgets = "*"
jsanimation = "*"
jupyter-contrib-nbextensions = "*"
nbstripout = "*"
notebook = ">=5.0.0,<5.1.0"
pydicom = {git = "https://github.com/cancan101/pydicom.git", editable = true, ref = "decode_source"}
pytest = "*"
requests = "*"


[requires]

python_version = "3.5"
```

**Comment by techalchemy** [comment] 2017-11-08 07:14
@cancan101 if you run `pipenv lock —clear —verbose` then does it remove the entry and/or generate any informative output?

**Comment by cancan101** [comment] 2017-11-08 07:18
Tried it. It did not remove the entry nor indicate any info about it.

**Comment by techalchemy** [comment] 2017-11-08 12:52
@cancan101 would you provide the output? The resolver takes your pipfile as it’s primary input. It doesnt do any introspection of your virtualenv. So the only way for a VCS dependency to get into the lockfile at the top level is if it is listed in your pipfile somewhere. 

Do you have a pipfile or requirements file one directory up? Two directories? What’s the output of `cwd` compared with `pipenv —where`?

**Comment by cancan101** [comment] 2017-11-08 15:17
This line in the pipenv file is causing the problems:
```
object_detection = {ref = "working", git = "https://github.com/cancan101/models.git", editable = true, subdirectory = "research"}
```

**Comment by techalchemy** [comment] 2017-11-17 05:07
To follow up I installed this repository and was unable to replicate the issue.  You have a lot of vcs repositories in your pipfile so it's not really that surprising that a lot of dependencies are getting resolved into your lockfile.  I'm going to close this issue since I can't reproduce it.

**Closed by techalchemy** 2017-11-17 05:07 UTC
