### ISSUE TITLE
Most pipenv commands result in OSError

### ISSUE THREAD

**Issue by elistevens** [kennethreitz/pipenv#195] opened 2017-02-03 04:46 UTC
This is Ubuntu 16.04, in a project dir that I'd like to start using pipenv with. Here's what I've run:

```$ history
 2034  virtualenv .venv
 2036  .venv/bin/pip install pipenv
 2039  pipenv shell
 2046  .venv/bin/pipenv check
```

The last two commands give stack traces like:

```$ .venv/bin/pipenv shell
Creating a virtualenv for this project...
Traceback (most recent call last):
  File ".venv/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/elis/edit/play/pytorch/.venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/elis/edit/play/pytorch/.venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/elis/edit/play/pytorch/.venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/elis/edit/play/pytorch/.venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/elis/edit/play/pytorch/.venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/elis/edit/play/pytorch/.venv/local/lib/python2.7/site-packages/pipenv/cli.py", line 880, in shell
    ensure_project(three=three, python=python, validate=False)
  File "/home/elis/edit/play/pytorch/.venv/local/lib/python2.7/site-packages/pipenv/cli.py", line 117, in ensure_project
    ensure_virtualenv(three=three, python=python)
  File "/home/elis/edit/play/pytorch/.venv/local/lib/python2.7/site-packages/pipenv/cli.py", line 100, in ensure_virtualenv
    do_create_virtualenv(three=three, python=python)
  File "/home/elis/edit/play/pytorch/.venv/local/lib/python2.7/site-packages/pipenv/cli.py", line 339, in do_create_virtualenv
    c = delegator.run(cmd, block=False)
  File "/home/elis/edit/play/pytorch/.venv/local/lib/python2.7/site-packages/delegator.py", line 215, in run
    c.run(block=block)
  File "/home/elis/edit/play/pytorch/.venv/local/lib/python2.7/site-packages/delegator.py", line 120, in run
    s = PopenSpawn(self._popen_args, **self._default_pexpect_kwargs)
  File "/home/elis/edit/play/pytorch/.venv/local/lib/python2.7/site-packages/pexpect/popen_spawn.py", line 45, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I can't tell if this is a bug or user error.

**Comment by nateprewitt** [comment] 2017-02-03 04:55
Hmm, this seems to be the same thing encountered in #190. I can't reproduce this on macOS or Ubuntu 14.04. I'll need to set up a VM with 16.04 and see if there's anything different there.

Are you using a standard bash shell, and are you trying to create this virtualenv while having a virtualenv active?

**Comment by elistevens** [comment] 2017-02-03 05:23
Default bash shell, yes.

And yes, I made a fresh `./.venv` before installing pipenv and running the commands. It's not "active" in the sense of the environment pointing to it, but I'm running the command as `.venv/bin/pipenv ...`

**Comment by holmars** [comment] 2017-02-11 12:22
@elistevens I had the same error yesterday on osx. I had installed `pipenv` with [pipsi](https://github.com/mitsuhiko/pipsi). The fix for me was to install `pew` with `pipsi` as well.

The issue is that `pew` needs to be in your `PATH` env var.

**Comment by nateprewitt** [comment] 2017-02-11 15:12
Thanks for taking the time to investigate this @holmars! I'm going to close this as resolved but feel free to reopen it if you continue experiencing this problem @elistevens.

**Closed by nateprewitt** 2017-02-11 15:12 UTC

**Comment by kennethreitz** [comment] 2017-02-11 17:26
luckily, this is in the documentation :)
