### ISSUE TITLE
Add support for setup.py files

### ISSUE THREAD

**Issue by Colin-b** [kennethreitz/pipenv#592] opened 2017-09-18 12:38 UTC
Hi,

Is it possible (or planned) for pipenv install command to check for setup.py file?

In order to extract dependencies from install_requires (and other extras_require sections).

Thanks and Regards

**Comment by techalchemy** [comment] 2017-09-18 13:33
Duplicate of #508 and #512

**Comment by kennethreitz** [comment] 2017-09-18 15:03
unfortunately, pip-tools does not support this feature.

**Comment by kennethreitz** [comment] 2017-09-18 17:35
If this issue is solved, we can tackle this: https://github.com/pypa/setuptools/issues/1153

**Comment by kennethreitz** [comment] 2017-09-18 17:39
e.g. currently, `setup.py --requires` does not work.

**Closed** 2017-09-18 23:45 UTC
Labels: enhancement

**Comment by kennethreitz** [comment] 2017-09-18 23:48
got this working! will be in v7.3.0

**Comment by kennethreitz** [comment] 2017-09-19 00:30
released

**Comment by sschuberth** [comment] 2017-09-21 08:24
So, does this mean `pipenv` should be able to import from `setup.py` in a similar way it does [from requirements.txt](http://docs.pipenv.org/en/latest/advanced.html#importing-from-requirements-txt)? I'm asking because I cannot get it to work in pipenv 7.3.7. E.g. when cloning https://github.com/nexB/scancode-toolkit and running `pipenv install`, the generated `Pipfile` is almost empty, whereas I would have expected it to contain the `install_requires` dependencies from `setup.py`.

**Comment by kennethreitz** [comment] 2017-09-21 14:00
no, that will not work

**Comment by kennethreitz** [comment] 2017-09-21 14:00
`pipenv install -e .`

**Comment by sschuberth** [comment] 2017-09-21 14:07
Please bear with me (I only occasionally do Python), but how do I know I need the `-e` in this case?

**Comment by kennethreitz** [comment] 2017-09-21 14:08
you want to install the current directory as editable.

**Comment by sschuberth** [comment] 2017-09-21 14:09
I know that the `-e` stands for "editable", but I would not have guessed that it's required, because I actually don't want to necessarily edit anything.

**Comment by kennethreitz** [comment] 2017-09-21 18:13
you want the current directory's changes to be reflected...

**Comment by kennethreitz** [comment] 2017-09-21 18:13
otherwise it will just be a snapshot of the current directory.
