### ISSUE TITLE
Cannot load zsh auto-completion

### ISSUE THREAD

**Issue by Zhomart** [kennethreitz/pipenv#324] opened 2017-04-20 23:47 UTC
If I tried what docs suggest it doesn't work at all:

```
$ cat ~/.zshrc
 eval (env _PIPENV_COMPLETE=source-zsh pipenv)
```

Then I tried following:

```
$ cat ~/.zshrc
 eval "$(env _PIPENV_COMPLETE=source-zsh pipenv)"
```

Now I get following error:

```
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]?
```

**Comment by nateprewitt** [comment] 2017-04-23 14:32
Hey @Zhomart, this was a feature implemented by @kennethreitz and I'm not entirely sure how it was originally supposed to function. He may have some insight on this.

**Comment by kennethreitz** [comment] 2017-04-23 18:21
the only documented (and tested) way of doing this is for fish, currently.

**Comment by kennethreitz** [comment] 2017-04-23 18:22
I'd look here for guidance: https://github.com/click-contrib/click-completion

**Comment by nateprewitt** [comment] 2017-04-28 17:15
I'm going to close this out since there doesn't seem to be anything further actionable here. Please feel free to let us know if you have any more information, questions, or reproducible examples, @Zhomart.

**Closed by nateprewitt** 2017-04-28 17:15 UTC
