### ISSUE TITLE
Tab completion under pipenv?

### ISSUE THREAD

**Issue by ColMcp** [kennethreitz/pipenv#497] opened 2017-09-08 16:38 UTC
macOS 10.12.6  Python 3.6.2  pipenv 6.1.6

When I run the CPython REPL from a standard shell tab completion is operative. When I run it via pipenv (`pipenv run python3`   or  `pipenv shell` then `python3`) tab completion is not operative. 

Is this a bug, or a configuration failure on my part?

**Comment by kennethreitz** [comment] 2017-09-08 16:39
I'm not sure! Very interesting. 

Can you test with a standard virtualenv and see if it's the same? Might be a pew side-effect.

**Comment by ColMcp** [comment] 2017-09-08 16:40
Tab completion is operative under a standard virtualenv.

**Comment by kennethreitz** [comment] 2017-09-08 16:41
Now create one with pew.

**Comment by kennethreitz** [comment] 2017-09-08 16:41
i believe it's `$ pew newvenv`

**Comment by ColMcp** [comment] 2017-09-08 16:45
The finger seems to point at pew  ...  tab completion is not operative.

**Comment by kennethreitz** [comment] 2017-09-08 16:54
Let's open an issue over there and link to it here!

**Comment by ColMcp** [comment] 2017-09-08 16:57
Will do.

**Comment by kennethreitz** [comment] 2017-09-08 16:57
✨🍰✨

**Comment by kennethreitz** [comment] 2017-09-08 17:01
so aparently this code activates tab complete:

```
import rlcompleter, readline
readline.parse_and_bind('tab: complete')
```

**Comment by kennethreitz** [comment] 2017-09-08 17:02
when i run this, it enables autocomplete.

**Comment by kennethreitz** [comment] 2017-09-08 17:02
maybe this code is being excluded from `site.py` or something, in pew.

**Comment by ColMcp** [comment] 2017-09-08 17:07
I opened https://github.com/berdario/pew/issues/150

**Comment by ColMcp** [comment] 2017-09-08 17:09
Will use the rlcompleter / readline code as a fix for now. Thanks!

**Comment by kennethreitz** [comment] 2017-09-08 17:14
Thanks for noticing this!

**Comment by ColMcp** [comment] 2017-09-08 17:43
Rather than the `parse_and_bind` call shown above I had to use
        `readline.parse_and_bind('bind ^I rl_complete')` .

 Maybe it's a macOS thing.

**Comment by kennethreitz** [comment] 2017-09-08 18:45
Interesting, it worked for me on MacOS.

**Comment by ColMcp** [comment] 2017-09-08 19:13
`site.py` from the Python library has the following code in `enablerlcompleter()`

        # Reading the initialization (config) file may not be enough to set a
        # completion key, so we set one first and then read the file.
        readline_doc = getattr(readline, '__doc__', '')
        if readline_doc is not None and 'libedit' in readline_doc:
            readline.parse_and_bind('bind ^I rl_complete')
        else:
            readline.parse_and_bind('tab: complete')

Maybe we have different arrangements for accessing a readline library on our respective machines.

**Comment by kennethreitz** [comment] 2017-09-08 19:34
@ColMcp can you add this as a comment on https://github.com/kennethreitz/pipenv/issues/497#issuecomment-328190362 ?

**Comment by kennethreitz** [comment] 2017-09-10 14:13
Closing for https://github.com/berdario/pew/issues/150

**Closed by kennethreitz** 2017-09-10 14:13 UTC

**Comment by ngirard** [comment] 2018-04-11 17:37
@woozyking how does
```
$ source $(pipenv --venv)/bin/activate
```
help in any manner ?

**Comment by woozyking** [comment] 2018-04-11 18:01
```
$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
source /Users/woozyking/.local/share/virtualenvs/test-HaxrPBoG/bin/activate
bash-3.2$ source /Users/woozyking/.local/share/virtualenvs/test-HaxrPBoG/bin/activate
(test-HaxrPBoG) bash-3.2$ # tab completion works partially, not working, for example git commands
```

```
$ source $(pipenv --venv)/bin/activate
(test-HaxrPBoG) woozyking-air:test woozyking$ # tab completion works
```

Not to say it's a definitive solution, but a work around (and may very well be superficial) that works.

**Comment by ngirard** [comment] 2018-04-11 20:53
@woozyking Thanks ! So this helps with the shell completion, and not the one from the python interpreter, right ?

**Comment by woozyking** [comment] 2018-04-11 20:54
@ngirard yep

**Comment by bbarker** [comment] 2018-05-03 20:46
I also had problem using tab-completion in `pip-env shell`, `source $(pipenv --venv)/bin/activate` works for me though. My situation: largely using packages, including python, from Nix pkgs on top of Ubuntu 16.04.

**Comment by nbeernink** [comment] 2018-05-31 18:47
Thanks @andyneff, that's very useful! :) I was disappointed to see that PYTHONSTARTUP is not read when [using inspect](https://docs.python.org/3/using/cmdline.html#cmdoption-i). And neither does the `source $(pipenv --venv)/bin/activate` workaround.

**Comment by wichert** [comment] 2018-07-27 12:50
@andyneff I still see the same problem with Python 3.7. Why did you test for Python 2 in your `.pyrc` ?

**Comment by andyneff** [comment] 2018-07-30 15:03
@wichert At the time, I was not having the same issue on my python 3. If you are, then by all means, remove the test for Python 2

**Comment by ericfrederich** [comment] 2018-09-19 12:41
Hi, consider re-opening this please.  It was closed after [a new bug was filed against pew](https://github.com/berdario/pew/issues/150).  However it doesn't seem they're going to fix it.  The issue is with `virtualenv`.

Indeed when I create a virtual environment with `virtualenv` tab completion does not work, however if I create one with `venv` it does.  Could `pipenv` use `venv` instead?

**Comment by uranusjr** [comment] 2018-09-20 03:31
(Note: If I sound frustrated, I am. It’s not really your fault, but because I need to say the same thing so many times.)

We’ve been through this many times in the issue tracker already. venv support is not currently viable because we can’t drop Python 2 support yet, and do not have resources to maintain two backends (or more, venv is not as compatible across Python releases as you might imagine).

If you want to help, try fix this for virtualenv.

**Comment by kennethreitz** [comment] 2018-09-20 05:10
venv also is inferior

**Comment by joshua-s** [comment] 2020-04-20 21:18
Python 2 is EOL now, so perhaps this could be revisited.

**Comment by sdykae** [comment] 2024-04-08 16:57
any updates?  I use the way `pipenv run python ./script.py` but i got large script directory now, and need to switch between multiple scripts, but autocompletion with tab does not work i have to know the name and location and is hard to keep track, the part that is missing completion is the file completion after the work python
