### ISSUE TITLE
Dependency could not be resolved when I used asterisk.

### ISSUE THREAD

**Issue by Kjwon15** [kennethreitz/pipenv#993] opened 2017-10-30 13:33 UTC
I am using `requests` and `pyrebase` as dependency to my project.
My Pipfile looks like this: (non-relevant are removed)
```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

requests = "*"
pyrebase = "*"


[dev-packages]


```

##### Describe you environment

1. OS Type: Ubuntu 17.10 artful
1. Python version: Python 3.6.2
1. Pipenv version: pipenv, version 8.3.1

##### Expected result

Install `requests 2.11.1` and goes well.

##### Actual result

Pipenv installs `requests 2.18.4`(which is latest version) and conflict with `pyrebase`(which requires `2.11.1`)

##### Steps to replicate

`pipenv install requests pyrebase`

**Comment by erinxocon** [comment] 2017-10-30 22:46
This is how our locking mechanism works.  The pipfile specifies the most recent version of requests, where as pyrebase specifically requests an older version.  Since pyrebase specifically requests an older version of requests, you get a conflict when you are trying to lock while also installing the most current version as it can't match them up.  

If you just install pyrebase, you will have access to requests as it will be in your site packages.  So you don't have to install requests again.  Everything actually installs ok, the way you are doing it, it just can't create a lock file for a deterministic build.  You can use the `--skip-lock` command to ignore this error message if you really need the most recent version of requests installed.

**Comment by Kjwon15** [comment] 2017-10-31 04:01
So `*` means *most recent* instead of wildcard?

**Comment by erinxocon** [comment] 2017-10-31 04:12
@Kjwon15 Indeed!

**Comment by nateprewitt** [comment] 2017-10-31 04:27
This seems like a bug to me. Shouldn't pip-tools be resolving the correct version of `requests` to install alongside `pyrebase`?

Is this a dupe of one of the many "our patched version of pip-tools is broken" tickets?

**Comment by techalchemy** [comment] 2017-10-31 04:39
@nateprewitt i think it’s an order of operations thing. I think if you specifically ask for requests = “*” it is technically pinning the most recent version of requests and then moving on. This is confusing I agree, considering I believe we advertise the syntax as ‘unpinned’ when converting from requirements.txt. If the intention is to strictly pin the most current version of everything I would imagine this could cause problems for people who think these are not pinned at all and assume we will resolve dependencies and land on versions with no conflicts (which seems preferable)

If you want strict pins that goes in the lockfile, I would think?

**Comment by erinxocon** [comment] 2017-10-31 04:49
I do think that they should be resolved along side pyrebase.  Also I think like @Kjwon15 the `*` means wild card more than most recent version.  Ideally, IMO, `*` should resolve to whatever version is needed by other packages, or the most recent if nothing requires it.  Unpinned implies wildcard not most recent version.

**Comment by tuukkamustonen** [comment] 2017-10-31 14:04
Not sure but I think this is related to https://github.com/pypa/pip/issues/988.

**Comment by techalchemy** [comment] 2017-10-31 14:16
@tuukkamustonen excellent thank you for the ref

**Comment by vphilippon** [comment] 2017-11-01 15:56
I'm can confirm this is related to the "we pin our selected candidate right away" issue I was talking about in https://github.com/kennethreitz/pipenv/issues/875#issuecomment-337717817 .

`pipenv lock --verbose` output on which I confirmed this:
```
$ pipenv lock --verbose
Locking [dev-packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1
Current constraints:

Finding the best candidates:

Finding secondary dependencies:
------------------------------------------------------------
Result of round 1: stable, done
Locking [packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1
Current constraints:
  pyrebase
  requests

Finding the best candidates:
  found candidate pyrebase==3.0.27 (constraint was <any>)
  found candidate requests==2.18.4 (constraint was <any>)

Finding secondary dependencies:
  requests==2.18.4          requires certifi>=2017.4.17, chardet<3.1.0,>=3.0.2, idna<2.7,>=2.5, requests==2.18.4, urllib3<1.23,>=1.21.1
  pyrebase==3.0.27          requires gcloud==0.17.0, oauth2client==3.0.0, pycryptodome==3.4.3, pyrebase==3.0.27, python_jwt==2.0.1, requests==2.11.1, requests_toolbelt==0.7.0

New dependencies found in this round:
  adding [u'certifi', '>=2017.4.17', '[]']
  adding [u'chardet', '<3.1.0,>=3.0.2', '[]']
  adding [u'gcloud', '==0.17.0', '[]']
  adding [u'idna', '<2.7,>=2.5', '[]']
  adding [u'oauth2client', '==3.0.0', '[]']
  adding [u'pycryptodome', '==3.4.3', '[]']
  adding [u'pyrebase', '==3.0.27', '[]']
  adding [u'python-jwt', '==2.0.1', '[]']
  adding [u'requests', '==2.11.1,==2.18.4', '[]']
  adding [u'requests-toolbelt', '==0.7.0', '[]']
  adding [u'urllib3', '<1.23,>=1.21.1', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  certifi>=2017.4.17
  chardet<3.1.0,>=3.0.2
  gcloud==0.17.0
  idna<2.7,>=2.5
  oauth2client==3.0.0
  pycryptodome==3.4.3
  pyrebase==3.0.27
  python_jwt==2.0.1
  requests==2.11.1,==2.18.4
  requests_toolbelt==0.7.0
  urllib3<1.23,>=1.21.1

Finding the best candidates:
  found candidate certifi==2017.7.27.1 (constraint was >=2017.4.17)
  found candidate chardet==3.0.4 (constraint was >=3.0.2,<3.1.0)
  found candidate gcloud==0.17.0 (constraint was ==0.17.0)
  found candidate idna==2.6 (constraint was >=2.5,<2.7)
  found candidate oauth2client==3.0.0 (constraint was ==3.0.0)
  found candidate pycryptodome==3.4.3 (constraint was ==3.4.3)
  found candidate pyrebase==3.0.27 (constraint was ==3.0.27)
  found candidate python_jwt==2.0.1 (constraint was ==2.0.1)
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches requests==2.11.1,==2.18.4
Tried: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.6, 0.10.7, 0.10.8, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.14.0, 0.14.1, 0.14.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 2.0.0, 2.0.0, 2.0.1, 2.0.1, 2.1.0, 2.1.0, 2.2.0, 2.2.0, 2.2.1, 2.2.1, 2.3.0, 2.3.0, 2.4.0, 2.4.0, 2.4.1, 2.4.1, 2.4.2, 2.4.2, 2.4.3, 2.4.3, 2.5.0, 2.5.0, 2.5.1, 2.5.1, 2.5.2, 2.5.2, 2.5.3, 2.5.3, 2.6.0, 2.6.0, 2.6.1, 2.6.1, 2.6.2, 2.6.2, 2.7.0, 2.7.0, 2.8.0, 2.8.0, 2.8.1, 2.8.1, 2.9.0, 2.9.0, 2.9.1, 2.9.1, 2.9.2, 2.9.2, 2.10.0, 2.10.0, 2.11.0, 2.11.0, 2.11.1, 2.11.1, 2.12.0, 2.12.0, 2.12.1, 2.12.1, 2.12.2, 2.12.2, 2.12.3, 2.12.3, 2.12.4, 2.12.4, 2.12.5, 2.12.5, 2.13.0, 2.13.0, 2.14.0, 2.14.0, 2.14.1, 2.14.1, 2.14.2, 2.14.2, 2.15.1, 2.15.1, 2.16.0, 2.16.0, 2.16.1, 2.16.1, 2.16.2, 2.16.2, 2.16.3, 2.16.3, 2.16.4, 2.16.4, 2.16.5, 2.16.5, 2.17.0, 2.17.0, 2.17.1, 2.17.1, 2.17.2, 2.17.2, 2.17.3, 2.17.3, 2.18.0, 2.18.0, 2.18.1, 2.18.1, 2.18.2, 2.18.2, 2.18.3, 2.18.3, 2.18.4, 2.18.4
```

**Comment by foodtooth** [comment] 2017-11-02 10:17
Perhaps I've had a related issue.

A new project with `Pipfile` like this:
```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

scrapy = "*"
pymongo = "*"


[dev-packages]
```

And simply typing `$ pipenv install` will end up with errors and not install anything:
```
$ pipenv install
Creating a virtualenv for this project…
⠋Using base prefix '/usr'
New python executable in /home/mike/.local/share/virtualenvs/crawler_center-fPr_NAho/bin/python                                                             
Installing setuptools, pip, wheel...done.                                                                                                                   

Virtualenv location: /home/mike/.local/share/virtualenvs/crawler_center-fPr_NAho
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches pymongo
Tried: (no version found at all)
```

**Comment by techalchemy** [comment] 2017-11-02 12:37
@foodtooth you haven’t provided enough information to determine if your issue has anything to do with this one. Please open a new issue and provide context about your environment and we can go from there

**Closed** 2017-11-22 00:23 UTC
Labels: dependency resolution
