### ISSUE TITLE
UnicodeDecodeError on Windows if directory name contains umlaut

### ISSUE THREAD

**Issue by MrLeeh** [kennethreitz/pipenv#828] opened 2017-10-04 11:14 UTC
I just discovered pipenv throwing an UnicodeDecodeError when it comes to creating a new virtual environment based on a directory containing umlauts. I guess that is due to the default encoding in Windows is   CP-1252 which is not compatible to utf-8.

    Traceback (most recent call last):
      File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "c:\python36\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Python36\Scripts\pipenv.exe\__main__.py", line 9, in <module>
      File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main

        rv = self.invoke(ctx)
      File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "c:\python36\lib\site-packages\pipenv\cli.py", line 1736, in install
        ensure_project(three=three, python=python, system=system, warn=True, deploy=deploy)
      File "c:\python36\lib\site-packages\pipenv\cli.py", line 588, in ensure_project
        ensure_virtualenv(three=three, python=python, site_packages=site_packages)
      File "c:\python36\lib\site-packages\pipenv\cli.py", line 559, in ensure_virtualenv
        do_create_virtualenv(python=python, site_packages=site_packages)
      File "c:\python36\lib\site-packages\pipenv\cli.py", line 929, in do_create_virtualenv
        click.echo(crayons.blue(c.out), err=True)
      File "c:\python36\lib\site-packages\pipenv\vendor\delegator.py", line 92, in out
        self.__out = self._pexpect_out
      File "c:\python36\lib\site-packages\pipenv\vendor\delegator.py", line 80, in _pexpect_out
        result += self.subprocess.read()
      File "c:\python36\lib\site-packages\pipenv\vendor\pexpect\spawnbase.py", line 413, in read
        self.expect(self.delimiter)
      File "c:\python36\lib\site-packages\pipenv\vendor\pexpect\spawnbase.py", line 321, in expect
        timeout, searchwindowsize, async)
      File "c:\python36\lib\site-packages\pipenv\vendor\pexpect\spawnbase.py", line 345, in expect_list
        return exp.expect_loop(timeout)
      File "c:\python36\lib\site-packages\pipenv\vendor\pexpect\expect.py", line 99, in expect_loop
        incoming = spawn.read_nonblocking(spawn.maxread, timeout)
      File "c:\python36\lib\site-packages\pipenv\vendor\pexpect\popen_spawn.py", line 86, in read_nonblocking
        buf += self._decoder.decode(incoming, final=False)
      File "c:\python36\lib\codecs.py", line 321, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 54: invalid continuation byte

**Comment by kennethreitz** [comment] 2017-10-06 13:46
Paging @erinxocon!

**Comment by erinxocon** [comment] 2017-10-07 07:09
Working on this now!

```python
C:\Users\Ajök Piñata よしもと\repos\pipenv [encoding-tests]
λ  pip3 install -e .
Obtaining file:///C:/Users/Aj%C3%B6k%20Pi%C3%B1ata%20%E3%82%88%E3%81%97%E3%82%82%E3%81%A8/repos/pipenv
Collecting virtualenv (from pipenv==8.2.7)
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 936kB/s
Collecting pew>=0.1.26 (from pipenv==8.2.7)
  Downloading pew-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: pip>=9.0.1 in c:\program files\python36\lib\site-packages (from pipenv==8.2.7)
Collecting requests>2.18.0 (from pipenv==8.2.7)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 5.9MB/s
Collecting flake8 (from pipenv==8.2.7)
  Downloading flake8-3.4.1-py2.py3-none-any.whl (68kB)
    100% |████████████████████████████████| 71kB ...
Collecting urllib3>=1.21.1 (from pipenv==8.2.7)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 6.6MB/s
Collecting virtualenv-clone>=0.2.5 (from pew>=0.1.26->pipenv==8.2.7)
  Downloading virtualenv-clone-0.2.6.tar.gz
Requirement already satisfied: setuptools>=17.1 in c:\program files\python36\lib\site-packages (from pew>=0.1.26->pipenv==8.2.7)
Collecting chardet<3.1.0,>=3.0.2 (from requests>2.18.0->pipenv==8.2.7)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 6.6MB/s
Collecting idna<2.7,>=2.5 (from requests>2.18.0->pipenv==8.2.7)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB ...
Collecting certifi>=2017.4.17 (from requests>2.18.0->pipenv==8.2.7)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 6.6MB/s
Collecting pyflakes<1.6.0,>=1.5.0 (from flake8->pipenv==8.2.7)
  Downloading pyflakes-1.5.0-py2.py3-none-any.whl (225kB)
    100% |████████████████████████████████| 225kB 6.6MB/s
Collecting mccabe<0.7.0,>=0.6.0 (from flake8->pipenv==8.2.7)
  Downloading mccabe-0.6.1-py2.py3-none-any.whl
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8->pipenv==8.2.7)
  Downloading pycodestyle-2.3.1-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 3.3MB/s
Installing collected packages: virtualenv, virtualenv-clone, pew, chardet, urllib3, idna, certifi, requests, pyflakes, mccabe, pycodestyle, flake8, pipenv
  Running setup.py install for virtualenv-clone ... done
  Running setup.py develop for pipenv
Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 35: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 845, in install
    install_options, global_options, prefix=prefix)
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 1007, in install_editable
    show_stdout=False)
  File "c:\program files\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 35: invalid start byte
C:\Users\Ajök Piñata よしもと\repos\pipenv [encoding-tests]
λ
```

Traceback for information

**Comment by erinxocon** [comment] 2017-10-07 19:19
@MrLeeh in your console can you execute the following commands and paste them here?  

`chcp` - should show the current active code page for the console

Another question...How are you running pipenv?  What version of python did you install pipenv with?  The problem happened when you tried to create a virtualenv from a directory that contained an umlaut correct?  I'm trying to see if this is a bug in pew or pipenv.

**Comment by MrLeeh** [comment] 2017-10-08 08:48
@erinxocon The current active code page which I obtained via `chcp`is 850 which according to Microsoft means Multilingual (Latin I). 

I'm running pipenv directly from the Windows Console. This means either `cmd.exe` or PowerShell. I also tried it with the conemu terminal emulator which came to the same result. I'm using Python 3.6.2. The pipenv version is 8.2.6. 

Yes, the problem occurs the moment I try to install a new virtual environment via `pipenv install`. 

Let me know if you need any more information.

Regards

**Comment by erinxocon** [comment] 2017-10-08 09:59
Can I ask for the name of the folder in question here?

**Comment by MrLeeh** [comment] 2017-10-08 10:03
The folder in question is `c:\Users\Stefan\Documents\python\täst`

**Comment by erinxocon** [comment] 2017-10-18 05:15
Sorry for taking so long for getting back.  Relooking at this now.

**Comment by MrLeeh** [comment] 2017-10-18 06:14
No worries. There's no rush here. Renaming is always a fallback option ;)

**Comment by erinxocon** [comment] 2017-10-24 08:15
@MrLeeh Using powershell I'm not able to reproduce this when I create a virtualenv using `pipenv --three` but can when using `pipenv --two`.  Not the same exact error of course, but similar.

**Comment by kennethreitz** [comment] 2017-11-22 00:29
known bug, wont fix for now

**Closed by kennethreitz** 2017-11-22 00:29 UTC
Labels: bug, help wanted, windows
