### ISSUE TITLE
Editables from pipfile are installed shallow

### ISSUE THREAD

**Issue by PaulVisscher** [kennethreitz/pipenv#1079] opened 2017-11-16 21:44 UTC
Dependencies of editables are not included in the lock file, so they do not get installed during a fresh `pipenv install`, this is due to the `no_deps` switch in https://github.com/kennethreitz/pipenv/blob/023696e46993bf55cd2807eae1801f8884a6357a/pipenv/cli.py#L775

A minimal example is demonstrated in the following gist
https://gist.github.com/PaulVisscher/f20d2d56fff66414b85ed77622a3aa66

##### Describe your environment

1. Debian GNU/Linux 8
1. Python version: Python 3.6.3
1. Pipenv version: 3.8.2

##### Expected result
Dependencies of editable packages are added to the lock file and installed

##### Actual result
Editable packages are installed shallow: dependencies of editable packages are not added to the lock file, and thus not installed.
```
pipenv shell
python
>>> import foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dummy/foo/foo/__init__.py", line 1, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
```

##### Steps to replicate
 - Replicate the structure from the linked [gist](https://github.com/kennethreitz/pipenv/blob/023696e46993bf55cd2807eae1801f8884a6357a/pipenv/cli.py#L775) or download the included test folder from the [test-case.zip](https://github.com/kennethreitz/pipenv/files/1480495/test-case.zip).
- Run
```
pipenv install
pipenv shell
````
- Run
```
python
>>> import foo
````

**Comment by dahluwalia-ag** [comment] 2017-11-17 21:32
I'm having the same issue (tested in Debian 8.7)... I'll put together a more helpful writeup shortly, but briefly:

I'm using setup.py to specify install_requires. I'm using Pipfile to reference the setup.py:
```
[packages]
"e1839a8" = {path=".", editable=true}
```

If I do **pipenv install** none of my "setup.py install_requires" stuff gets installed.
If I do: **pipenv install --skip-lock** all packages get installed properly.

And of course, outside of pipenv, the setup.py file works well by doing:
**python setup.py install** or
**python setup.py develop** or
**pip install -e .**

**Comment by techalchemy** [comment] 2017-11-18 00:08
yes, this is indeed an issue.

you don't need to do much more of a writeup unless you can point at the cause (or more helpfully the solution!)

I am kind of thinking this relates to our other dependency resolution issues now that I've spent a bunch of time on that issue...

**Comment by techalchemy** [comment] 2017-11-18 00:10
@PaulVisscher the reason `no_deps` is true there is because the deps of editable files are supposed to be resolved into the lockfile, which is the real problem here.

**Comment by kennethreitz** [comment] 2017-11-22 00:18
this is a current implementation design decision

**Closed** 2017-11-22 00:18 UTC
Labels: bug, dependency resolution
