### ISSUE TITLE
Pipenv is really slow to exit if the network is not working

### ISSUE THREAD

**Issue by anowlcalledjosh** [kennethreitz/pipenv#1023] opened 2017-11-02 16:56 UTC
When the network is very slow, Pipenv takes an extremely long time to exit after doing almost anything (e.g. `pipenv` will print the usage message, and then block for a while – but `pipenv --help` will behave as normal).

##### Describe your environment

1. OS Type: Ubuntu 16.04
1. Python version: 3.6.3
1. Pipenv version: 8.3.1, installed via pipsi

Here is the result of `pip list` in the virtualenv that Pipenv is installed in:

```
Package          Version    
---------------- -----------
certifi          2017.7.27.1
chardet          3.0.4      
flake8           3.5.0      
idna             2.6        
mccabe           0.6.1      
pew              1.1.0      
pip              9.0.1      
pipenv           8.3.1      
pycodestyle      2.3.1      
pyflakes         1.6.0      
requests         2.18.4     
setuptools       36.6.0     
urllib3          1.22       
virtualenv       15.1.0     
virtualenv-clone 0.2.6      
wheel            0.30.0
```

##### Expected result

Pipenv shouldn't suddenly take longer to exit because the network is behaving strangely.

##### Actual result

If the network is slow, it takes almost exactly 21 seconds to run many Pipenv commands, including:

- `pipenv`
- `pipenv --completion`

but *not* `pipenv --help` (finishes in about 1 second, regardless of network state AFAICT).

If I press ctrl-C after running `pipenv`, when it has printed the usage message but not yet exited, I get a traceback like this:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Exception ignored in: <function ThreadPoolExecutor._adjust_thread_count.<locals>.weakref_cb at 0x7fce19f11a60>
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 131, in weakref_cb
  File "/usr/lib/python3.6/queue.py", line 145, in put
  File "/usr/lib/python3.6/threading.py", line 347, in notify
TypeError: 'NoneType' object is not callable
```

##### Steps to replicate

~~Have a WiFi card that randomly decides to stop working~~ Run `sudo tc qdisc add dev INTERFACE root netem delay 10s` (where `INTERFACE` might be something like `wlp2s0` – obtain it from either `ip link` or `ifconfig`) to add a 10s delay to all your traffic, then run `pipenv`.

The delay can then be removed with `sudo tc qdisc del dev INTERFACE root netem`.

[Source for these commands](http://bencane.com/2012/07/16/tc-adding-simulated-network-latency-to-your-linux-server/)

**Comment by nateprewitt** [comment] 2017-11-02 17:01
I've got a strong feeling this is related to pipenv trying to check if it needs to update on every call. This is a lot of added overhead even if we move it to a background thread because we still have to wait for that to complete before exiting. I haven't taken a deep look at the background decorator but that was my initial understanding when it was written.

**Comment by nateprewitt** [comment] 2017-11-02 17:01
@erinxocon didn't you help implement some of that?

**Comment by erinxocon** [comment] 2017-11-02 18:06
@nateprewitt I did, I can look at this later tonight after work.

**Comment by techalchemy** [comment] 2017-11-02 21:53
@anowlcalledjosh that's actually a super neat way to emulate network latency too, thanks for the tip!

**Comment by erinxocon** [comment] 2017-11-03 02:49
@nateprewitt I can confirm that this is the issue.  Short of disabling the check on every call (which I'm not convinced is necessary anyways) I'm not sure how to solve it.  We are using the timeout parameter on the requests call, but that will only end the thread if the server hasn't responded in half a second, not if it's responded but taking a while to send the rest of the data...

**Comment by nateprewitt** [comment] 2017-11-03 02:59
Yeah, Requests only supports read and write timeouts, not overall. A slow network connection won't let the timeout trip unless it's REALLY slow.

I don't have a great heuristic we can use to determine if we should run the check, but I don't think it makes sense to run it every time. I'm also curious if this is part of the issue in #953.

For options here, I can see us either doing nothing (🙁), find a good way to determine if we should check, move it to a command/option so it's manual, or add another environment variable to disable stuff (also kind of 🙁 but it would work).

**Comment by erinxocon** [comment] 2017-11-03 03:14
@nateprewitt We have a command/flag for it, --upgrade, will check and upgrade pipenv.  The check actually instructs you to use that command if it finds a newer release.  If we do want to do a check automatically, maybe like once a week or something?  I don't know how we track when the last time the user invoked the command was. So perhaps just leaving it as a manual upgrade with the flag for now?

**Comment by techalchemy** [comment] 2017-11-03 03:16
@nateprewitt @erinxocon what if we make note of the last time we checked for updates, and say by default we only check every 24 hours or once a week...  We can pickle or shelve or store in sqlite a datetime in the user-specific cache dir whenever the last check was

**Comment by techalchemy** [comment] 2017-11-03 03:17
@erinxocon @nateprewitt ignore that, even better we just touch the file whenever we check, then we can just see the last time the file was updated...

**Comment by nateprewitt** [comment] 2017-11-03 03:22
@erinxocon, @techalchemy, I think given our current release cycle, once a week is fine. We could also do 24hr without a huge penalty. Simply touching the file seems like a good approach to me too. The main goal here is to remove the network call from the average use case.

**Comment by erinxocon** [comment] 2017-11-03 03:31
I'm currently working on an enhancement around this that looks at the last time the pipfile was modifed and checks if it's been 24 hours.  Is that cool?

**Comment by techalchemy** [comment] 2017-11-03 03:34
@erinxocon would that still work if the user edits it by hand? Or if they run `pipenv install <x>` but it doesn't also check for updates?

**Comment by erinxocon** [comment] 2017-11-03 03:34
@techalchemy Sorry I meant Pipfile.lock

**Comment by techalchemy** [comment] 2017-11-03 03:36
@erinxocon but then do we force an update check whenever they generate / update the lockfile?

**Comment by erinxocon** [comment] 2017-11-03 03:37
@techalchemy On generation and then after 24 hours since the last modification.  Since only pipenv should be updating the lockfile I thought that this may be a better approach.

**Comment by erinxocon** [comment] 2017-11-03 03:38
`--skip-lock` would bypass this, but I think that's getting into a fringe usecase

**Comment by nateprewitt** [comment] 2017-11-03 03:44
Mmm, so I think I may have misunderstood what we were discussing touching. We probably don't want to do this on the Pipfile or Pipfile.lock because anyone using multiple projects will hit this check the first time they check each project that day.

I guess that's slightly better but still an odd user experience. Pipenv itself is probably not editable by the process which is good. Have we considered a unique file in the /tmp/ directory?

**Comment by erinxocon** [comment] 2017-11-03 03:47
@nateprewitt Good point.  We could use a unqie file in the /tmp/ directory, don't see why that wouldn't be device independent and work.

**Comment by techalchemy** [comment] 2017-11-03 03:50
Right, but why not just use the user cache dir?

**Comment by techalchemy** [comment] 2017-11-03 03:50
^ that was what I meant when I mentioned it at first

**Comment by nateprewitt** [comment] 2017-11-03 04:01
@techalchemy, yeah that's a fine option too. We just need something that isn't tied to each project and unlikely to be edited.

**Comment by techalchemy** [comment] 2017-11-03 04:44
I'm putting up a PR for this, feel free to not accept it and / or cherrypick ideas from it if you want, I just thought it would be more helpful than me yammering on about it in here if you could just see what i mean in code

**Comment by erinxocon** [comment] 2017-11-04 01:43
@anowlcalledjosh this should be fixed in master shortly and will be included in the next release! @nateprewitt think we can do a v8.3.2 release for this functionality or should we wait until there is some more stuff in the release.

**Closed by erinxocon** 2017-11-04 01:43 UTC

**Comment by nateprewitt** [comment] 2017-11-04 17:38
v8.3.2 released.
