### ISSUE TITLE
Pipenv ignores active environment and creates new virtualenv anyway

### ISSUE THREAD

**Issue by justinmayer** [kennethreitz/pipenv#289] opened 2017-03-24 15:16 UTC
As recently as Pipenv v3.3.6, I manually created my own virtual environment, installed Pipenv into it, and used Pipenv to manage project packages within that already-active virtual environment.

But since then there seems to have been a change that disrupts that workflow, and now Pipenv appears to ignore the active virtual environment and insists on creating its own virtual environment with an appended hash.

## Steps to reproduce

    > fish --version
    fish, version 2.5.0

    > echo $WORKON_HOME
    /Users/me/virtualenvs

    > vf new -p python3 foo  # manual creation of `foo` virtual environment

    > (foo) echo $VIRTUAL_ENV
    /Users/me/virtualenvs/foo

    > (foo) pip install pipenv

    > (foo) pipenv --version
    pipenv, version 3.5.4

    > (foo) pipenv install django==1.11rc1
    Creating a Pipfile for this project...
    Creating a virtualenv for this project...

## Expected result

Pipenv would use the currently-active virtual environment.

## Observed result

Pipenv ignores the currently-active virtual environment and creates a new environment, as seen above.

## Additional notes

I sincerely hope this is merely a bug, and that the answer to this is not, "Virtualenv is behaving as intended." I say this because (1) Pipenv supported this use case last month, and (2) I believe that Pipenv should support this use case: namely, installing Pipenv into a virtual environment, installing packages into that already-active virtual environment, and not insisting on creating its own virtual environment. I suspect this was introduced in a81197d, but that's just a guess.

In addition to other problems, this change breaks automatic linking of projects and virtual environments based on identical naming conventions. Up until now, I have always been able to `workon foo`, which automatically activates the `foo` environment and switches to the `~/projects/foo` directory. This change breaks that automation.

**Comment by nateprewitt** [comment] 2017-03-24 16:05
Hey @justinmayer, thanks for raising this issue. So, this is kind of a hard tradeoff. While I understand the pain of the new naming scheme for `pew` projects, we had a pretty good reason for doing so. If you have a project `foo`, prior to 3.5.0, which was downloaded onto your machine from github and deployed it would use the `foo` virtualenv. If you later cloned that repository *anywhere* onto the same machine and tried to run `pipenv` your deployment environment was silently deleted due to name collisions. While you can enact governance to avoid this, the failure mode was pretty unpleasant.

The use case of pipenv using the already activated virtualenv prior to 3.5.0 was purely coincidental and not intended behaviour. It happened to work because the activated virtualenv shared the same name as the project you were intending to use. If you moved to another directory, it would use `pipenv` commands on that directory rather than your currently activated virtualenv. So in my mind, what you were using pipenv for was in the realm of undefined behaviour.

That said, I'm willing to look into adding an official feature that will check the `$VIRTUAL_ENV` variable and use that as the "working" directory for pipenv commands. I'm worried this behaviour will cause more confusion than it helps, due to people forgetting they have a virtualenv activated and accidentally nuking their space when trying to create a new project in a new directory. Pipenv has previously been intended to be run without having to activate the virtualenv at all which has been one of the main advantages.

I'll leave this for @kennethreitz to weigh in on before we proceed with any functionality changes.

**Comment by kennethreitz** [comment] 2017-03-24 16:39
well, we have `--system` for this functionality, currently.

**Comment by nateprewitt** [comment] 2017-03-24 16:46
Yep, I guess that would have that effect when the virtualenv is activated. That will probably make things behave like you'd expect @justinmayer from a "use the virtualenv I have activated" perspective. As for `workon <project-name>`, I think you're still going to have to specify which environment you want. You can use `pew ls` for quick lookup of what's available though, so if you're using unique names `pew ls | grep 'foo'` should give you your project name. Creating an alias for that should be fairly easy for automation.

**Comment by justinmayer** [comment] 2017-03-24 18:16
Hey @nateprewitt / @kennethreitz. Many thanks for your quick responses and insightful info.

I looked into the `--system` option, and assuming I understand correctly that it allows Pip to install into global system-wide site-packages, then I'm not sure that option adequately addresses the use case I described above. I never want Pipenv to install anything outside of a virtual environment, and it seems to me that this option might lead to that result if there is no currently-active virtual environment. Feel free to correct me if my understanding is wrong.

As @nateprewitt suggested, I think that adding an official feature that checks the $VIRTUAL_ENV variable and uses that as the "working" directory for `pipenv` commands sounds great. I understand the potential issue of folks not realizing they have a virtual environment active, but one of the many benefits of Pipenv is the ease with which the environment can be restored. 😊

**Comment by nateprewitt** [comment] 2017-03-28 15:11
Hey @justinmayer, sorry for the delayed response.

`--system` will install for the current symlink to `pip`, which will be in your virtualenv when it's active. You're correct though that it will install to the system `pip` installation if the virtualenv isn't activated. So at this point we're discussing what is the more common case.

As I said above regarding using `$VIRTUAL_ENV`,
>  I'm worried this behaviour may cause more confusion than it helps though. Mainly due to people forgetting they have a virtualenv activated and accidentally nuking their space when trying to create a new project in a new directory. Pipenv has previously been intended to be run without having to activate the virtualenv at all which has been one of the main advantages.

Moving away from the "command you run works in the current directory" paradigm is a pretty big deviation for the average user. We've only received one report asking for this so far (and @jacebrowning's +1). Making a fundamental shift like that for what I would consider more of an edge case seems wrong to me. Verifying whether you're in a virtualenv is pretty trivial in most shells with the prompt, where as remembering an environment variable you exported `n` hours/days ago seems much more likely to be forgotten. I'd rather place the responsibility on the user to properly check their environment before using `--system`, than silently injecting another environment based on hidden environment state.

**Comment by jnns** [comment] 2017-04-03 22:48
> We've only received one report asking for this so far (and @jacebrowning's +1). 

I know that replying with ' +1' is frowned upon but since you're considering this to be an edge case I just quickly wanted to state that I ran into this problem twice already this week:

After working in my virtualenv and installing a package via `pipenv` I was puzzled by my app not being able to load the newly installed module until I found out that the new module had been installed in a newly created env with a hashed-name.

**Comment by jefftriplett** [comment] 2017-04-04 00:22
I'm hitting the same edge case as @jnns and @jacebrowning. I too was hesitant to chime in, but I'd love to see pipenv play nice with existing virtualenvs. 

I tried to rebuild a few projects to use it and I was running in to corner cases that virtualenv + virtualenv-wrapper already solve. Having the ability to work within an existing projects would make converting to pipenv's default much easier. 

If that's not in the scope of pipenv then I totally respect that.

**Comment by drcongo** [comment] 2017-04-12 11:00
To add my use case to this issue, I'm currently trying to build an Ansible role to configure web builds using Pipenv - these web builds typically have only one virtualenv which for various reasons we need at the same level as the project. I've tried everything in the docs to get it to create the the venv at the project level (WORKON_HOME, PROJECT_HOME, PIPENV_VENV_IN_PROJECT all set in /etc/environment), and with that last one, I've even got Ansible creating a .venv folder first to ensure there's an existing venv for it to use. Run through Ansible though, Pipenv always creates the virtualenv at `/root/.local/share/virtualenvs/vagrant-[HASH]` or whichever home Ansible's user owns.

While not exactly the same issue, the ability to do what earlier posters are describing may solve this.

**Comment by ajmazurie** [comment] 2017-05-25 21:56
Chiming in as well; I'm already using `pyenv` and `direnv` to automatically create virtual environments for Python interpreters, and **`pipenv`** would be a welcome addition if it could make use of these existing environments rather than creating new ones. Saying this, I realize what I really need is an updated version of `pip` that manages `Pipfile`s.

**Comment by kennethreitz** [comment] 2017-05-25 22:57
@ajmazurie you could help make that happen (potentially!)

**Comment by gregplaysguitar** [comment] 2017-05-29 03:03
Where has the `--system` option gone? Our workflow relied on it... is there some other way to use pipenv to install to the system, or to a custom-named virtualenv?

**Comment by nateprewitt** [comment] 2017-05-29 16:43
@gregplaysguitar, I don't believe the `--system` has gone anywhere. This question doesn't seem related to this issue though. Could you please open a new issue with steps to reproduce the issue and the current version of pipenv you're using? Thanks!

**Comment by gregplaysguitar** [comment] 2017-05-29 19:59
@nateprewitt sorry, there was some discussion about --system further up in the thread as a workaround for this issue. I've created a new one: #384

**Comment by gregplaysguitar** [comment] 2017-05-30 19:21
> I realize what I really need is an updated version of pip that manages Pipfiles.

@kennethreitz @ajmazurie I'd be willing to help out with this :)

Any advice as to where to start would be welcome.

**Closed** 2017-09-05 22:04 UTC

**Comment by justinmayer** [comment] 2017-09-05 23:05
For anyone else who comes across this issue, automatic utilization of the active virtual environment was addressed via #395 and included in the 5.0.0 release. Many thanks to @kennethreitz for implementing this feature! 😁 👍
