### ISSUE TITLE
lock file issue

### ISSUE THREAD

**Issue by kakulukia** [kennethreitz/pipenv#357] opened 2017-05-15 19:15 UTC
An error occured while installing!
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing; python_version <= "3.4" from https://pypi.python.org/packages/17/75/3698d7992a828ad6d7be99c0a888b75ed173a9280e53dbae67326029b60e/typing-3.6.1.tar.gz#md5=3fec97415bae6f742fb3c3013dedeb89 (from ipython==6.0.0->-r /tmp/tmptUdjF8-requirements.txt (line 34))

This is the mentioned requirements file, which generated by pipenv only has == in there:
`static3==0.7.0 --hash=sha256:674641c64bc75507af2eb20bef7e7e3593dca993dec6674be108fa15b42f47c8
six==1.10.0 --hash=sha256:0ff78c403d9bccf5a425a6d31a12aa6b47f1c21ca4dc2573a7e2f32a97335eb1
django-appconf==1.0.2 --hash=sha256:ddab987d14b26731352c01ee69c090a4ebfc9141ed223bef039d79587f22acd9
Willow==0.4 --hash=sha256:b86334bc1939bf6b3c33bbfe141d61600ed4e6880ac86408431400cd7cc7ba3f
django-crispy-forms==1.6.1 --hash=sha256:18e904c7bd55c45201739cb343272767ff820263a1fca40a7b388006ce94910c
wagtailgeowidget==3.1.1 --hash=sha256:19e987da8a3f06bc1ee1644684ee2aead8faf7d929bc653231fdb858a40f23b6
packaging==16.8 --hash=sha256:99276dc6e3a7851f32027a68f1095cd3f77c148091b092ea867a351811cfe388
django-modelcluster==3.1 --hash=sha256:9edde7fb87b413c1114df47f928e95fbd6878de17f9f2caeea90e77766e272b5
dj-static==0.0.6 --hash=sha256:032ec1c532617922e6e3e956d504a6fb1acce4fc1c7c94612d0fda21828ce8ef
pyparsing==2.2.0 --hash=sha256:fee43f17a9c4087e7ed1605bd6df994c6173c1e977d7ade7b651292fab2bd010
html5lib==0.999999999 --hash=sha256:b8934484cf22f1db684c0fae27569a0db404d0208d20163fbf51cc537245d008
appdirs==1.4.3 --hash=sha256:d8b24664561d0d34ddfaec54636d502d7cea6e29c3eaf68f3df6180863e2166e
django-libsass==0.7 --hash=sha256:49db3334b87e1f7955c4f9fb9945bc296f8bfd27a14d6d89706e4b0e5dc5de1c
pexpect==4.2.1 --hash=sha256:f853b52afaf3b064d29854771e2db509ef80392509bde2dd7a6ecf2dfc3f0018
ipdb==0.10.3 --hash=sha256:9ea256b4280fbe12840fb9dfc3ce498c6c6de03352eca293e4400b0dfbed2b28
rjsmin==1.0.12 --hash=sha256:dd9591aa73500b08b7db24367f8d32c6470021f39d5ab4e50c7c02e4401386f1
jedi==0.10.2 --hash=sha256:96678411f2ffa444da3a5e7fdd4adc513b728a4a4617b30308be5c950722424b
ptyprocess==0.5.1 --hash=sha256:464cb76f7a7122743dd25507650db89cd447c51f38e4671602b3eaa2e38e05ae
libsass==0.12.3 --hash=sha256:c3ea0cbb36745b6cc10278539e0bf93a426f2f497306181fc6214193f493b8d5
djangorestframework==3.6.3 --hash=sha256:bb9d55997a71fb1c844cd84c15cbe2e87d2ec8493a685f96aa3db403760626b7
django-taggit==0.22.1 --hash=sha256:969a68dc244fd3051589b6b917e26777cdf186f95dd51bf2f023f5446e2ca89e
webencodings==0.5.1 --hash=sha256:a0af1213f3c2226497a97e2b3aa01a7e4bee4f403f95be16fc9acd2947514a78
rcssmin==1.0.6 --hash=sha256:ca87b695d3d7864157773a61263e5abb96006e9ff0e021eff90cbe0e1ba18270
ipython_genutils==0.2.0 --hash=sha256:72dd37233799e619666c9f639a9da83c34013a73e8bbc79a7a6348d93c61fab8
django_compressor==2.1.1 --hash=sha256:6483f6091d614b2f3ddaa0d5061849e7bd40528f4f1fdf0d74e48df09e7c6699
Unidecode==0.04.20 --hash=sha256:eedac7bfd886f43484787206f6a141b232e2b2a58652c54d06499b187fd84660
appnope==0.1.0 --hash=sha256:5b26757dc6f79a3b7dc9fab95359328d5747fcb2409d331ea66d0272b90ab2a0
traitlets==4.3.2 --hash=sha256:c6cb5e6f57c5a9bdaa40fa71ce7b4af30298fbab9ece9815b5d995ab6217c7d9
tornado==4.5.1 --hash=sha256:db0904a28253cfe53e7dedc765c71596f3c53bb8a866ae50123320ec1a7b73fd
Django==1.11.1 --hash=sha256:bb3109a31cfa016e5f234223665f80fc06107f2169afb9f6dc8828295db73547
django-extensions==1.7.9 --hash=sha256:a6b97ec77657e4fd43d508d6a134c799f188e868717f7499d05213b4669b44b6
wagtail==1.10 --hash=sha256:49cc9ea8e25160b06ab2ad454ef63d32db9f0c2321b8d919b153dd9cd996e230
prompt_toolkit==1.0.14 --hash=sha256:7281b5199235adaef6980942840c43753e4ab20dfe41338da634fb41c194f9d8
ipython==6.0.0 --hash=sha256:9cdbfa1af3a92cf019d1a592646e27159b3cac1ab9f2be7643d5e3bc413d3b5c
beautifulsoup4==4.6.0 --hash=sha256:11a9a27b7d3bddc6d86f59fb76afb70e921a25ac2d6cc55b40d072bd68435a76
pickleshare==0.7.4 --hash=sha256:c9a2541f25aeabc070f12f452e1f2a8eae2abd51e1cd19e8430402bdf4c1d8b5
Pillow==4.1.1 --hash=sha256:f4fb801bfd2bcbfc4a7f2819c95ea6a1cfef197420ae9849b01b08b9970a51b3
decorator==4.0.11 --hash=sha256:73cbaadb8bc4e3c65fe1100773d56331a2d756cc0f5c7b9d8d5d5223fe04f600
olefile==0.44 --hash=sha256:61f2ca0cd0aa77279eb943c07f607438edf374096b66332fae1ee64a6f0f73ad
django-livereload-server==0.2.3 --hash=sha256:9450af6e0ad1866a1b5b787f98f9354fa2e4ceb38e135405019f630798b294cf
django-treebeard==4.1.0 --hash=sha256:f13c9a612a554ee0784632961904870efcf05f58282cd158da84ee88120fbafb
pytz==2017.2 --hash=sha256:d1d6729c85acea5423671382868627129432fba9a89ecbb248d8d1c7a9f01c67
wcwidth==0.1.7 --hash=sha256:f4ebe71925af7b40a864553f761ed559b43544f8f71746c2d756c7fe788ade7c
Pygments==2.2.0 --hash=sha256:78f3f434bcc5d6ee09020f92ba487f95ba50f1e3ef83ae96b9d5ffa1bab25c5d
setuptools==35.0.2 --hash=sha256:19d753940f8cdbee7548da318f8b56159aead279ef811a6efc8b8a33d89c86a4
requests==2.14.2 --hash=sha256:3b39cde35be51762885631cf586f4dc2284951b44d479a4454020758d767cc2f
simplegeneric==0.8.1 --hash=sha256:dc972e06094b9af5b855b3df4a646395e43d1c9d0d39ed345b7393560d0b9173%`

Whats wrong?

**Comment by kakulukia** [comment] 2017-05-15 19:17
ok just by posting i bet its a dependency of a dependency of ipython, but this should be taken care of by the pipenv lock command .. no?

**Comment by nateprewitt** [comment] 2017-05-15 19:50
Hey @kakulukia, this is a conditional dependency for iPython. I'm not actually able to reproduce this though.

Could you please provide the following info?
  * Python version
  * Pipenv version
  * Pipfile contents
  * Commands used

Thanks!

**Comment by kakulukia** [comment] 2017-05-16 03:04
Python 3.4.2
pipenv 3.6.2
i used pipenv install with this pipfile:
`[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages]
ipdb = "*"
ipython = "*"
wagtail = "*"
Django = "==1.10.7"
wagtailgeowidget = "*"
django-extensions = "*"
django-livereload-server = "*"
django_compressor = "*"
django-libsass = "*"
django-crispy-forms = "*"
dj-static = "*"

[packages.pyjade]
git = "https://github.com/syrusakbary/pyjade.git"
ref = "d8cf1d9404c759c6a2430c9a900874ab0e970cd8"`

**Comment by kakulukia** [comment] 2017-05-16 03:20
Besides not installing my dependencies pipenv install is insanely slow compared to pip install -r requirements.txt .. but lets compare again, when it actually works :/

**Comment by nateprewitt** [comment] 2017-05-16 13:31
Thanks @kakulukia! This should be helpful in debugging things, I'll let you know if I need anything further. I'm trying to get things together for PyCon at the moment but I'll try to get some investigation done on the plane tonight.

The slowness issue is related to how we add packages but has been solved. The fix is breaking though, so it won't be released until the next major version of pipenv (possibly the next release). You can keep an eye on #356 to track progress.

**Comment by kakulukia** [comment] 2017-05-17 13:56
looking forward to the new version .. and in the mean time i use pipenv and pip side by side :)

**Comment by nateprewitt** [comment] 2017-05-17 17:36
I'm unfortunately unable to reproduce this with the current environment info and provided Pipfile. Could you clarify what you mean by `--require-hashes` mode in your first comment? We've never had a flag like that, and hashes should be on by default in 3.6.2.

Here's the steps I'm trying, could you confirm this matches your appraoch?

* Create a project directory with a `Pipfile` containing your above contents
* `pipenv --python python3.4` (I have 3.4.2 installed)
* `pipenv install`
* `cat Pipfile.lock | grep -A 3 'typing'`

The last command returns what I'd expect, the `typing` package with a pinned version and hash.

```json
        "typing": {
            "hash": "sha256:c36dec260238e7464213dcd50d4b5ef63a507972f5780652e835d0228d0edace",
            "version": "==3.6.1"
        },
```

**Comment by nateprewitt** [comment] 2017-05-23 20:06
Hey @kakulukia, without more information, I'm not sure much can be done here. I'm going to close this out for now, but please let me know if you have any followup on the comment above. Thanks!

**Closed by nateprewitt** 2017-05-23 20:06 UTC
Labels: needs more information

**Comment by mlosev** [comment] 2018-01-10 16:57
I am getting similar issue with the following generated `requirements.txt`

```
boto==2.47.0 --hash=sha256:daa8cd950d546b848c907676aa3a57bbbc1486700646d13be9a01485794821ad  --hash=sha256:684ccaa1c030acd8ec6a48664d0555a6042bdc325b15ce52645c085bc36c0a69
cached-property==1.3.1 --hash=sha256:fe045921fe75c873064028e9fbbe06121114ccf613227f4ba284fa7d4c9ff27f  --hash=sha256:6562f0be134957547421dda11640e8cadfa7c23238fc4e0821ab69efdb1095f3
certifi==2017.11.5 --hash=sha256:244be0d93b71e93fc0a0a479862051414d0e00e16435707e5bf5000f92e04694  --hash=sha256:5ec74291ca1136b40f0379e1128ff80e866597e4e2c1e755739a913bbc3613c0
chardet==3.0.4 --hash=sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691  --hash=sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae
dnspython==1.15.0 --hash=sha256:861e6e58faa730f9845aaaa9c6c832851fbf89382ac52915a51f89c71accdd31  --hash=sha256:40f563e1f7a7b80dc5a4e76ad75c23da53d62f1e15e6e517293b04e1f84ead7c
docker==2.7.0 --hash=sha256:c1d4e37b1ea03b2b6efdd0379640f6ea372fefe56efa65d4d17c34c6b9d54558  --hash=sha256:144248308e8ea31c4863c6d74e1b55daf97cc190b61d0fe7b7313ab920d6a76c
docker-compose==1.18.0 --hash=sha256:4abb290b3ebb91314942532f1333d7f729c66254bde4b0756718291b7df42a7a  --hash=sha256:2930cbfe2685018fbb75377600ab6288861d9955717b3f14212f63950351d379
docker-pycreds==0.2.1 --hash=sha256:58d2688f92de5d6f1a6ac4fe25da461232f0e0a4c1212b93b256b046b2d714a9  --hash=sha256:93833a2cf280b7d8abbe1b8121530413250c6cd4ffed2c1cf085f335262f7348
dockerpty==0.4.1 --hash=sha256:69a9d69d573a0daa31bcd1c0774eeed5c15c295fe719c61aca550ed1393156ce
docopt==0.6.2 --hash=sha256:49b3a825280bd66b3aa83585ef59c4a8c82f2c8a522dbe754a8bc8d08c85c491
flake8==3.5.0 --hash=sha256:c7841163e2b576d435799169b78703ad6ac1bbb0f199994fc05f700b2a90ea37  --hash=sha256:7253265f7abd8b313e3892944044a365e3f4ac3fcdcfb4298f55ee9ddf188ba0
hvac==0.2.17 --hash=sha256:9e277a7864927f53fb1aca4fd33559390da43b21b6dc0c99058cf05ac8d5335f  --hash=sha256:2a4f7ea68d55caa90eae6d417765efb7fa31337e095cd69bcf7af0b3f7620270
idna==2.6 --hash=sha256:8c7309c718f94b3a625cb648ace320157ad16ff131ae0af362c9f21b80ef6ec4  --hash=sha256:2c6a5de3089009e3da7c5dde64a141dbc8551d5b7f6cf4ed7c2568d0cc520a8f
jinja2==2.9.6 --hash=sha256:2231bace0dfd8d2bf1e5d7e41239c06c9e0ded46e70cc1094a0aa64b0afeb054  --hash=sha256:ddaa01a212cd6d641401cb01b605f4a4d9f37bfc93043d7f760ec70fb99ff9ff
jsonschema==2.6.0 --hash=sha256:000e68abd33c972a5248544925a0cae7d1125f9bf6c58280d37546b946769a08  --hash=sha256:6ff5f3180870836cae40f06fa10419f557208175f13ad7bc26caa77beb1f6e02
markupsafe==1.0 --hash=sha256:a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665
mccabe==0.6.1 --hash=sha256:ab8a6258860da4b6677da4bd2fe5dc2c659cff31b3ee4f7f5d64e79735b80d42  --hash=sha256:dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f
netaddr==0.7.19 --hash=sha256:56b3558bd71f3f6999e4c52e349f38660e54a7a8a9943335f73dfc96883e08ca  --hash=sha256:38aeec7cdd035081d3a4c306394b19d677623bf76fa0913f6695127c7753aefd
pycodestyle==2.3.1 --hash=sha256:6c4245ade1edfad79c3446fadfc96b0de2759662dc29d07d80a6f27ad1ca6ba9  --hash=sha256:682256a5b318149ca0d2a9185d365d8864a768a28db66a84a2ea946bcc426766
pyflakes==1.6.0 --hash=sha256:08bd6a50edf8cffa9fa09a463063c425ecaaf10d1eb0335a7e8b1401aef89e6f  --hash=sha256:8d616a382f243dbf19b54743f280b80198be0bca3a5396f1d2e1fca6223e8805
python-consul==0.7.0 --hash=sha256:f5725067586f0119a4eb50bbc8daca75c86791d1c002b97fc173f2347d2dfaa1
pyyaml==3.12 --hash=sha256:3262c96a1ca437e7e4763e2843746588a965426550f3797a79fca9c6199c431f  --hash=sha256:16b20e970597e051997d90dc2cddc713a2876c47e3d92d59ee198700c5427736  --hash=sha256:e863072cdf4c72eebf179342c94e6989c67185842d9997960b3e69290b2fa269  --hash=sha256:bc6bced57f826ca7cb5125a10b23fd0f2fff3b7c4701d64c439a300ce665fff8  --hash=sha256:c01b880ec30b5a6e6aa67b09a2fe3fb30473008c85cd6a67359a1b15ed6d83a4  --hash=sha256:827dc04b8fa7d07c44de11fabbc888e627fa8293b695e0f99cb544fdfa1bf0d1  --hash=sha256:592766c6303207a20efc445587778322d7f73b161bd994f227adaa341ba212ab  --hash=sha256:5f84523c076ad14ff5e6c037fe1c89a7f73a3e04cf0377cb4d017014976433f3  --hash=sha256:0c507b7f74b3d2dd4d1322ec8a94794927305ab4cebbe89cc47fe5e81541e6e8  --hash=sha256:b4c423ab23291d3945ac61346feeb9a0dc4184999ede5e7c43e1ffb975130ae6  --hash=sha256:ca233c64c6e40eaa6c66ef97058cdc80e8d0157a443655baa1b2966e812807ca  --hash=sha256:4474f8ea030b5127225b8894d626bb66c01cda098d47a2b0d3429b6700af9fd8  --hash=sha256:326420cbb492172dec84b0f65c80942de6cedb5233c413dd824483989c000608  --hash=sha256:5ac82e411044fb129bae5cfbeb3ba626acb2af31a8d17d175004b70862a741a7
requests==2.18.4 --hash=sha256:6a1b267aa90cac58ac3a765d067950e7dbbf75b1da07e895d1f594193a40a38b  --hash=sha256:9c443e7324ba5b85070c4a818ade28bfabedf16ea10206da1132edaa6dda237e
six==1.11.0 --hash=sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb  --hash=sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9
texttable==0.9.1 --hash=sha256:119041773ff03596b56392532f9315cb3a3116e404fd6f36e76a7dc088d95c79
urllib3==1.22 --hash=sha256:06330f386d6e4b195fbfc736b297f58c5a892e4440e54d294d7004e3a9bbea1b  --hash=sha256:cc44da8e1145637334317feebd728bd869a35285b93cbb4cca2577da7e62db4f
websocket-client==0.46.0 --hash=sha256:7a40abbd2534c91e667ca6507ccbb30d96816361840ef424dff49b24956fcdae  --hash=sha256:933f6bbf08b381f2adbca9e93d7e7958ba212b42c73acb310b18f0fbe74f3738
```

and after putting this to `requirements.txt` and using `pip install -r` I get the following error

```
Collecting websocket-client==0.46.0 (from -r /requirements.txt (line 27))
  Downloading websocket_client-0.46.0-py2.py3-none-any.whl (200kB)
Collecting backports.ssl-match-hostname>=3.5; python_version < "3.5" (from docker==2.7.0->-r /requirements.txt (line 6))
Collecting ipaddress>=1.0.16; python_version < "3.3" (from docker==2.7.0->-r /requirements.txt (line 6))
Collecting enum34<2,>=1.0.4; python_version < "3.4" (from docker-compose==1.18.0->-r /requirements.txt (line 7))
Collecting configparser; python_version < "3.2" (from flake8==3.5.0->-r /requirements.txt (line 11))
Collecting functools32; python_version == "2.7" (from jsonschema==2.6.0->-r /requirements.txt (line 15))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    backports.ssl-match-hostname>=3.5; python_version < "3.5" from https://pypi.python.org/packages/76/21/2dc61178a2038a5cb35d14b61467c6ac632791ed05131dda72c20e7b9e23/backports.ssl_match_hostname-3.5.0.1.tar.gz#md5=c03fc5e2c7b3da46b81acf5cbacfe1e6 (from docker==2.7.0->-r /requirements.txt (line 6))
    ipaddress>=1.0.16; python_version < "3.3" from https://pypi.python.org/packages/f0/ba/860a4a3e283456d6b7e2ab39ce5cf11a3490ee1a363652ac50abf9f0f5df/ipaddress-1.0.19.tar.gz#md5=d0687efaf93a32476d81e90ba0609c57 (from docker==2.7.0->-r /requirements.txt (line 6))
    enum34<2,>=1.0.4; python_version < "3.4" from https://pypi.python.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl#md5=68f6982cc07dde78f4b500db829860bd (from docker-compose==1.18.0->-r /requirements.txt (line 7))
    configparser; python_version < "3.2" from https://pypi.python.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz#md5=cfdd915a5b7a6c09917a64a573140538 (from flake8==3.5.0->-r /requirements.txt (line 11))
    functools32; python_version == "2.7" from https://pypi.python.org/packages/5e/1a/0aa2c8195a204a9f51284018562dea77e25511f02fe924fac202fc012172/functools32-3.2.3-2.zip#md5=d55232eb132ec779e6893c902a0bc5ad (from jsonschema==2.6.0->-r /requirements.txt (line 15))
```

seems like transitive dependencies are not present in `Pipfile.lock` and therefore are not having exact version as `--require-hashes` mode demands

however `pipenv graph` show all dependencies (even transitive) with exact versions installed

---
My `Pipfile` is as follows

```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

"flake8" = "==3.5.0"
PyYAML = "==3.12"
"Jinja2" = "==2.9.6"
python-consul = "==0.7.0"
docker-compose = "==1.18.0"
hvac = "==0.2.17"
boto = "==2.47.0"
dnspython = "==1.15.0"
netaddr = "==0.7.19"


[dev-packages]



[requires]

python_version = "2.7"
```

`pipenv graph` as follows:

```
boto==2.47.0
colorama==0.3.9
dnspython==1.15.0
docker-compose==1.18.0
  - backports.ssl-match-hostname [required: >=3.5, installed: 3.5.0.1]
  - cached-property [required: >=1.2.0,<2, installed: 1.3.1]
  - docker [required: <3.0,>=2.6.1, installed: 2.7.0]
    - backports.ssl-match-hostname [required: >=3.5, installed: 3.5.0.1]
    - docker-pycreds [required: >=0.2.1, installed: 0.2.1]
      - six [required: >=1.4.0, installed: 1.11.0]
    - ipaddress [required: >=1.0.16, installed: 1.0.19]
    - requests [required: >=2.14.2,!=2.18.0, installed: 2.18.4]
      - certifi [required: >=2017.4.17, installed: 2017.11.5]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.7, installed: 2.6]
      - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
    - six [required: >=1.4.0, installed: 1.11.0]
    - websocket-client [required: >=0.32.0, installed: 0.46.0]
      - six [required: Any, installed: 1.11.0]
  - dockerpty [required: <0.5,>=0.4.1, installed: 0.4.1]
    - six [required: >=1.3.0, installed: 1.11.0]
  - docopt [required: <0.7,>=0.6.1, installed: 0.6.2]
  - enum34 [required: >=1.0.4,<2, installed: 1.1.6]
  - ipaddress [required: >=1.0.16, installed: 1.0.19]
  - jsonschema [required: >=2.5.1,<3, installed: 2.6.0]
    - functools32 [required: Any, installed: 3.2.3.post2]
  - PyYAML [required: <4,>=3.10, installed: 3.12]
  - requests [required: <2.19,!=2.11.0,!=2.12.2,!=2.18.0,>=2.6.1, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2017.11.5]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.7, installed: 2.6]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - six [required: >=1.3.0,<2, installed: 1.11.0]
  - texttable [required: <0.10,>=0.9.0, installed: 0.9.1]
  - websocket-client [required: >=0.32.0,<1.0, installed: 0.46.0]
    - six [required: Any, installed: 1.11.0]
flake8==3.5.0
  - configparser [required: Any, installed: 3.5.0]
  - enum34 [required: Any, installed: 1.1.6]
  - mccabe [required: <0.7.0,>=0.6.0, installed: 0.6.1]
  - pycodestyle [required: >=2.0.0,<2.4.0, installed: 2.3.1]
  - pyflakes [required: <1.7.0,>=1.5.0, installed: 1.6.0]
hvac==0.2.17
  - requests [required: >=2.7.0, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2017.11.5]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.7, installed: 2.6]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
Jinja2==2.9.6
  - MarkupSafe [required: >=0.23, installed: 1.0]
netaddr==0.7.19
python-consul==0.7.0
  - requests [required: >=2.0, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2017.11.5]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.7, installed: 2.6]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - six [required: >=1.4, installed: 1.11.0]
```
