### ISSUE TITLE
AttributeError: 'time.struct_time' object has no attribute 'tm_day'

### ISSUE THREAD

**Issue by sametmax** [kennethreitz/pipenv#804] opened 2017-10-01 19:13 UTC
In a 3.6 virtualenv on Ubuntu:

```
python -m pipenv  
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/user/.local/share/virtualenvs/test/lib/python3.6/site-packages/pipenv/__init__.py", line 17, in <module>
    from .cli import cli
  File "/home/user/.local/share/virtualenvs/test/lib/python3.6/site-packages/pipenv/cli.py", line 78, in <module>
    if ((now.tm_mon == 10) and (now.tm_day == 30)) or ((now.tm_mon == 10) and (now.tm_day == 31)):
AttributeError: 'time.struct_time' object has no attribute 'tm_day'
```

**Comment by nateprewitt** [comment] 2017-10-01 19:26
@sametmax, this is a duplicate of #738. You'll need to upgrade to 8.2.5 to fix this. Please do a quick check on the issue tracker before opening new issues. Thanks!

**Closed by nateprewitt** 2017-10-01 19:26 UTC
