### ISSUE TITLE
Pipenv cannot be used with PaaS providers (Heroku) due to hash conflicts

### ISSUE THREAD

**Issue by jacebrowning** [kennethreitz/pipenv#250] opened 2017-03-03 14:29 UTC
This is a duplicate of https://github.com/kennethreitz/pipenv/issues/210, but I want to resurface the issue with a broader scope.

-----

The systems that I develop, test, and lock my dependencies on are different from the systems I deploy to so the `Pipfile.lock` committed to the repository will cause hash conflicts during deployment if any of my dependencies have changed.

For Heroku, my workaround is to the delete the `Pipfile.lock` in the "pre-compile" phase of  deployment, but this completely nullifies the goal of having reproducible deployments.

**Comment by kennethreitz** [comment] 2017-03-09 01:49
this seems to be caused by different versions of python, specifically.

**Comment by kennethreitz** [comment] 2017-03-12 04:47
heroku's integration works around this :)

we will introduce an `--ignore-hashes` option, however.

**Comment by jacebrowning** [comment] 2017-03-12 22:12
> heroku's integration works around this :)

I'm not sure what that means... the buildpack?

> we will introduce an `--ignore-hashes` option, however.

👍

**Comment by kennethreitz** [comment] 2017-03-12 22:13
yes

**Comment by nateprewitt** [comment] 2017-03-12 22:30
Given `--ignore-hashes` is now supported in 3.5.3, I think we can close this out. I'll make a note of the option in the documentation.

**Closed by nateprewitt** 2017-03-12 22:30 UTC
