### ISSUE TITLE
Easter Egg breaking builds

### ISSUE THREAD

**Issue by audiolion** [kennethreitz/pipenv#798] opened 2017-10-01 15:22 UTC
```
  File "/root/.local/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File "/root/.local/lib/python2.7/site-packages/pipenv/__init__.py", line 17, in <module>
    from .cli import cli
  File "/root/.local/lib/python2.7/site-packages/pipenv/cli.py", line 89, in <module>
    if ((now.tm_mon == 10) and (now.tm_day == 30)) or ((now.tm_mon == 10) and (now.tm_day == 31)):
AttributeError: 'time.struct_time' object has no attribute 'tm_day'
Exited with code 1
```

Python 2.7.12 on Linux

edit: I just looked at git blame and I think a fix was implemented, let me try updating pipenv

**Comment by nateprewitt** [comment] 2017-10-01 15:24
Hey @audiolion, this is a duplicate of #783 from yesterday, please upgrade to the latest pipenv version.

**Closed by nateprewitt** 2017-10-01 15:24 UTC
