### ISSUE TITLE
Double requirement

### ISSUE THREAD

**Issue by singleton11** [kennethreitz/pipenv#167] opened 2017-01-31 05:48 UTC
```
[[source]]
verify_ssl = true
url = "https://pypi.python.org/simple"

[packages]
django = "*"
django-cacheops = "*"
django-cors-headers = "*"
factory-boy = "*"
django-allauth = "*"
django-crispy-forms = "*"
django-filter = "*"
django-hstore = "*"
django-imagekit = "*"
django-model-utils = "*"
djangorestframework = "*"
djangorestframework-gis = "*"
djangorestframework-hstore = "*"
drf-nested-routers = "*"
django-taggit-serializer = "*"
django-rest-auth = "0.8.2"
pdfkit = "*"
django-storages-redux = "*"
boto = "*"
django-taggit = "*"
pilkit = "*"
pillow = "*"
psycopg2 = "*"
pytz = "*"
redis = "*"
sendgrid-django = "*"
twilio = "*"
inflection = "*"
django-localflavor = "*"
opbeat = "*"
boltons = "*"
django-push-notifications = "*"
django-extensions = "*"

[dev-packages]
coverage = "*"
django-coverage-plugin = "*"
werkzeug = "*"
django-test-plus = "*"
flake8 = "*"
pep8 = "*"
autopep8 = "*"
django-debug-toolbar = "*"
ipdb = "*"
ipython = "*"
ipython-genutils = "*"
pylama = "*"
jedi = "*"
importmagic = "*"
elpy = "*"
yapf = "*"
django-jenkins = "*"
sphinx = "*"
sphinxcontrib-napoleon = "*"
sphinx-rtd-theme = "*"
sphinx-autobuild = "*"

```
django double etc, you know! :)

**Comment by nateprewitt** [comment] 2017-01-31 05:55
Sorry @singleton11, you're going to have to be a bit more explicit. This is a pretty dense Pipfile and I'm not immediately seeing the issue. I'm assuming this is related to #90?

**Comment by nateprewitt** [comment] 2017-01-31 06:04
@singleton11, the issue is you're using incorrect syntax for `django-rest-auth`. The entry needs to be `django-rest-auth = "==0.8.2"` if you want exactly version 0.8.2.

Feel free to reopen this if you're still having issues.

**Comment by singleton11** [comment] 2017-01-31 06:23
Pipfile:
```
[[source]]
verify_ssl = true
url = "https://pypi.python.org/simple"

[packages]
django = "*"
django-cacheops = "*"
django-cors-headers = "*"
factory-boy = "*"
django-allauth = "*"
django-crispy-forms = "*"
django-filter = "*"
django-hstore = "*"
django-imagekit = "*"
django-model-utils = "*"
djangorestframework = "*"
djangorestframework-gis = "*"
djangorestframework-hstore = "*"
drf-nested-routers = "*"
django-taggit-serializer = "*"
django-rest-auth = "==0.8.2"
pdfkit = "*"
django-storages-redux = "*"
boto = "*"
django-taggit = "*"
pilkit = "*"
pillow = "*"
psycopg2 = "*"
pytz = "*"
redis = "*"
sendgrid-django = "*"
twilio = "*"
inflection = "*"
django-localflavor = "*"
opbeat = "*"
boltons = "*"
django-push-notifications = "*"
django-extensions = "*"

[dev-packages]
coverage = "*"
django-coverage-plugin = "*"
werkzeug = "*"
django-test-plus = "*"
flake8 = "*"
pep8 = "*"
autopep8 = "*"
django-debug-toolbar = "*"
ipdb = "*"
ipython = "*"
ipython-genutils = "*"
pylama = "*"
jedi = "*"
importmagic = "*"
elpy = "*"
yapf = "*"
django-jenkins = "*"
sphinx = "*"
sphinxcontrib-napoleon = "*"
sphinx-rtd-theme = "*"
sphinx-autobuild = "*"
```

Pipfile.lock:
```
{
    "develop": {
        "pygments": {
            "hash": "sha256:78f3f434bcc5d6ee09020f92ba487f95ba50f1e3ef83ae96b9d5ffa1bab25c5d",
            "version": "==2.2.0"
        },
        "pyflakes": {
            "hash": "sha256:cc5eadfb38041f8366128786b4ca12700ed05bbf1403d808e89d57d67a3875a7",
            "version": "==1.5.0"
        },
        "ptyprocess": {
            "hash": "sha256:464cb76f7a7122743dd25507650db89cd447c51f38e4671602b3eaa2e38e05ae",
            "version": "==0.5.1"
        },
        "django-coverage-plugin": {
            "hash": "sha256:2d0caf343d632f13eb8e91d8fa521a8a42a0a6acad5803cb436b53f837dbe1cb",
            "version": "==1.4.1"
        },
        "werkzeug": {
            "hash": "sha256:c6f6f89124df0514d886782c658c3e12f2caaa94da34cee3fd82eebf4ebf052b",
            "version": "==0.11.15"
        },
        "autopep8": {
            "hash": "sha256:a2ab1a03a58c8d664ee875ca73d5b96b7135c13863e9aad4b64b888acdeb619b",
            "version": "==1.2.4"
        },
        "appdirs": {
            "hash": "sha256:85e58578db8f29538f3109c11250c2a5514a2fcdc9890d9b2fe777eb55517736",
            "version": "==1.4.0"
        },
        "importmagic": {
            "hash": "sha256:3f7757a5b74c9a291e20e12023bb3bf71bc2fa3adfb15a08570648ab83eaf8d8",
            "version": "==0.1.7"
        },
        "sphinx-autobuild": {
            "hash": "sha256:2f9262d7a35f80a18c3bcb03b2bf5a83f0a5e88b75ad922b3b1cee512c7e5cd2",
            "version": "==0.6.0"
        },
        "ipython-genutils": {
            "hash": "sha256:6218e9abd612fb5acfb175ea7c7b026006de4df9691d9a73c9b390cfa1a41c2b",
            "version": "==0.1.0"
        },
        "imagesize": {
            "hash": "sha256:6ebdc9e0ad188f9d1b2cdd9bc59cbe42bf931875e829e7a595e6b3abdc05cdfb",
            "version": "==0.7.1"
        },
        "elpy": {
            "hash": "sha256:dc0d349885f4fb774a68c81f26700ddef437c339775aebf2eb23535e7c5784ec",
            "version": "==1.14.0"
        },
        "decorator": {
            "hash": "sha256:73cbaadb8bc4e3c65fe1100773d56331a2d756cc0f5c7b9d8d5d5223fe04f600",
            "version": "==4.0.11"
        },
        "yapf": {
            "hash": "sha256:0f6c616db25d28c7874940206bdcc40baa26d99e3128457c45e22b3d3965d545",
            "version": "==0.15.2"
        },
        "pytz": {
            "hash": "sha256:a1ea35e87a63c7825846d5b5c81d23d668e8a102d3b1b465ce95afe1b3a2e065",
            "version": "==2016.10"
        },
        "six": {
            "hash": "sha256:0ff78c403d9bccf5a425a6d31a12aa6b47f1c21ca4dc2573a7e2f32a97335eb1",
            "version": "==1.10.0"
        },
        "django-test-plus": {
            "hash": "sha256:3a27340c1ff219004eec4e042037f4c05df0aa7a78909197831d4d84c66a67e6",
            "version": "==1.0.16"
        },
        "MarkupSafe": {
            "hash": "sha256:a4ec1aff59b95a14b45eb2e23761a0179e98319da5a7eb76b56ea8cdc7b871c3",
            "version": "==0.23"
        },
        "sphinx": {
            "hash": "sha256:57c8636e1d23f6c01fb19911a8f255f1b4934ba69feb55bd4dd0f097ebb04f05",
            "version": "==1.5.2"
        },
        "django-debug-toolbar": {
            "hash": "sha256:62f95c09c0faa4b2deac7edba69a84d0d8ad794e79ce24d86c7cd004c91053d8",
            "version": "==1.6"
        },
        "pockets": {
            "hash": "sha256:7c1246b3a5a08e85256af13fa239f5bf8dc9bf78b690472e02702b341dad4a78",
            "version": "==0.3.1"
        },
        "setuptools": {
            "hash": "sha256:edd9d39782fe38b9c533002b2e6fdf06498793cbd29266accdcc519431d4b7ba",
            "version": "==34.1.0"
        },
        "ipdb": {
            "hash": "sha256:fffc45b615e46eb75becbd88a30c69c75e7164ecd0122f2c78579b4dfa41b8c9",
            "version": "==0.10.2"
        },
        "port_for": {
            "hash": "sha256:b16a84bb29c2954db44c29be38b17c659c9c27e33918dec16b90d375cc596f1c",
            "version": "==0.3.1"
        },
        "livereload": {
            "hash": "sha256:422de10d7ea9467a1ba27cbaffa84c74b809d96fb1598d9de4b9b676adf35e2c",
            "version": "==2.5.1"
        },
        "babel": {
            "hash": "sha256:3318ed2960240d61cbc6558858ee00c10eed77a6508c4d1ed8e6f7f48399c975",
            "version": "==2.3.4"
        },
        "pexpect": {
            "hash": "sha256:f853b52afaf3b064d29854771e2db509ef80392509bde2dd7a6ecf2dfc3f0018",
            "version": "==4.2.1"
        },
        "ipython": {
            "hash": "sha256:fa2486bc71c46d267b05aa177652617c111609454152d390a8302a3a239c27af",
            "version": "==5.2.0"
        },
        "pycodestyle": {
            "hash": "sha256:6c4245ade1edfad79c3446fadfc96b0de2759662dc29d07d80a6f27ad1ca6ba9",
            "version": "==2.3.1"
        },
        "simplegeneric": {
            "hash": "sha256:dc972e06094b9af5b855b3df4a646395e43d1c9d0d39ed345b7393560d0b9173",
            "version": "==0.8.1"
        },
        "prompt-toolkit": {
            "hash": "sha256:20e7c776b5f3a5b2d1332921592172325d70105e21b8768e204098ad504fc742",
            "version": "==1.0.10"
        },
        "pickleshare": {
            "hash": "sha256:c9a2541f25aeabc070f12f452e1f2a8eae2abd51e1cd19e8430402bdf4c1d8b5",
            "version": "==0.7.4"
        },
        "snowballstemmer": {
            "hash": "sha256:9f3bcd3c401c3e862ec0ebe6d2c069ebc012ce142cce209c098ccb5b09136e89",
            "version": "==1.2.1"
        },
        "flake8": {
            "hash": "sha256:dc9eed7667489b73b56b1714aa51f580601db364b61e1833908e931c6de47a65",
            "version": "==3.2.1"
        },
        "pathtools": {
            "hash": "sha256:7c35c5421a39bb82e58018febd90e3b6e5db34c5443aaaf742b3f33d4655f1c0",
            "version": "==0.1.2"
        },
        "alabaster": {
            "hash": "sha256:d3e64a74919373d6d4d1d36bd717206584cb64cbb0532dfce3bc2081cba6817b",
            "version": "==0.7.9"
        },
        "mccabe": {
            "hash": "sha256:ab8a6258860da4b6677da4bd2fe5dc2c659cff31b3ee4f7f5d64e79735b80d42",
            "version": "==0.6.1"
        },
        "wcwidth": {
            "hash": "sha256:f4ebe71925af7b40a864553f761ed559b43544f8f71746c2d756c7fe788ade7c",
            "version": "==0.1.7"
        },
        "packaging": {
            "hash": "sha256:99276dc6e3a7851f32027a68f1095cd3f77c148091b092ea867a351811cfe388",
            "version": "==16.8"
        },
        "pylama": {
            "hash": "sha256:bd2d848c00096d906af4d2fe0ce2008389cd8d1e7d2e3a43d4f785db141d13c5",
            "version": "==7.3.3"
        },
        "sphinx-rtd-theme": {
            "hash": "sha256:46c2ca8b482b0398b9621bb5a8ec7c9c5c7226926e5363e18d744f5f0d39d78f",
            "version": "==0.1.9"
        },
        "argh": {
            "hash": "sha256:a9b3aaa1904eeb78e32394cd46c6f37ac0fb4af6dc488daa58971bdc7d7fcaf3",
            "version": "==0.26.2"
        },
        "pydocstyle": {
            "hash": "sha256:20939fb9c2d61a9870449573d9ed762ec040c764b2241bec22c5ea956b9caf90",
            "version": "==1.1.1"
        },
        "docutils": {
            "hash": "sha256:cb3ebcb09242804f84bdbf0b26504077a054da6772c6f4d625f335cc53ebf94d",
            "version": "==0.13.1"
        },
        "sqlparse": {
            "hash": "sha256:9b61c319b3c7b64681e1b4d554a9c3fe81ed52da00a901ccf3fe72962734e444",
            "version": "==0.2.2"
        },
        "jedi": {
            "hash": "sha256:51f2521a257bbc5ef036fddeaf29168e1312782fc580c5e889e53dba41ea730d",
            "version": "==0.9.0"
        },
        "Jinja2": {
            "hash": "sha256:a7b7438120dbe76a8e735ef7eba6048eaf4e0b7dbc530e100812f8ec462a4d50",
            "version": "==2.9.5"
        },
        "coverage": {
            "hash": "sha256:b25aa3531220faaf1727fc29bc000798476b4a30f429dc07898d5da48caefa15",
            "version": "==4.3.4"
        },
        "pyparsing": {
            "hash": "sha256:67101d7acee692962f33dd30b5dce079ff532dd9aa99ff48d52a3dad51d2fe84",
            "version": "==2.1.10"
        },
        "requests": {
            "hash": "sha256:1a720e8862a41aa22e339373b526f508ef0c8988baf48b84d3fc891a8e237efb",
            "version": "==2.13.0"
        },
        "sphinxcontrib-napoleon": {
            "hash": "sha256:45aeb259eeecd6a641fcea45adb0a0268bbe92117ab52e7c919cd6bfc36fe548",
            "version": "==0.6.0"
        },
        "Django": {
            "hash": "sha256:4541a60834f28f308ee7b6e96400feca905fb0de473eb9dad6847e98a36d86d4",
            "version": "==1.10.5"
        },
        "PyYAML": {
            "hash": "sha256:592766c6303207a20efc445587778322d7f73b161bd994f227adaa341ba212ab",
            "version": "==3.12"
        },
        "watchdog": {
            "hash": "sha256:7e65882adb7746039b6f3876ee174952f8eaaa34491ba34333ddf1fe35de4162",
            "version": "==0.8.3"
        },
        "tornado": {
            "hash": "sha256:2898f992f898cd41eeb8d53b6df75495f2f423b6672890aadaf196ea1448edcc",
            "version": "==4.4.2"
        },
        "pep8": {
            "hash": "sha256:4fc2e478addcf17016657dff30b2d8d611e8341fac19ccf2768802f6635d7b8a",
            "version": "==1.7.0"
        },
        "traitlets": {
            "hash": "sha256:50522e46dd7b66c80686d50ff1b774000f1d2a80c84b2bcfbd657d588e99a368",
            "version": "==4.3.1"
        },
        "django-jenkins": {
            "hash": "sha256:2dda72ffc85311612cadf400b90900be4972867e074daf1f1602c607a9899ba8",
            "version": "==0.110.0"
        }
    },
    "_meta": {
        "requires": {},
        "hash": {
            "sha256": "32d5445a3df1a6101941a7fe68bfd4c0c01b3f093cae73f60f578513bf1fa1ac"
        },
        "sources": [
            {
                "verify_ssl": true,
                "url": "https://pypi.python.org/simple"
            }
        ]
    },
    "default": {
        "django-cors-headers": {
            "hash": "sha256:638aaba85f96af62557656ec559672f03d7c61769685acc405eacfaba9d4e93f",
            "version": "==2.0.1"
        },
        "django": "*",
        "pdfkit": {
            "hash": "sha256:05f1c631e8d9ab877886955da825e48b459e097886a21448ab17b34c60cfd66c",
            "version": "==0.6.1"
        },
        "oauthlib": {
            "hash": "sha256:132ad46df25e53a84b33f1fd43f80e973cda2cb018cc0168d7d0c8c4d5cef9b5",
            "version": "==2.0.1"
        },
        "requests-oauthlib": {
            "hash": "sha256:87e1c05c1b4b4220af0c7ff4e6572ff7fba8032166cb1a12d2e1acd4a5fdaf4f",
            "version": "==0.7.0"
        },
        "django-allauth": {
            "hash": "sha256:231f1e980dee8ee56be4f64e6a4b77cb32b41d977e6ea6bd310b2c8c0bc354bb",
            "version": "==0.30.0"
        },
        "django-imagekit": {
            "hash": "sha256:592cac00874d18b79a7fda2135b20dc46c3a2337d26e1c8dcda0004a66fac445",
            "version": "==3.3"
        },
        "django-storages-redux": {
            "hash": "sha256:84cb0e685ac0401f14d320d3d469b3e5968a7314a93936c86672c2315d8302dc",
            "version": "==1.3.2"
        },
        "defusedxml": {
            "hash": "sha256:cd551d5a518b745407635bb85116eb813818ecaf182e773c35b36239fc3f2478",
            "version": "==0.4.1"
        },
        "drf-nested-routers": {
            "hash": "sha256:edaa03541acd83d90b80453eba588e239ebb989b096211e27ef8dbde2355d79b",
            "version": "==0.11.1"
        },
        "django-filter": {
            "hash": "sha256:7cca9dab22c72df734ba24fb81ca018fdb6d2020c840e758d473dcedd341aa7b",
            "version": "==1.0.1"
        },
        "django-cacheops": {
            "hash": "sha256:06ea0994ebe7853c391bf2c8b846cab8157ea110ee3d6c9cf22f5296bfdd9294",
            "version": "==3.1.1"
        },
        "pytz": {
            "hash": "sha256:a1ea35e87a63c7825846d5b5c81d23d668e8a102d3b1b465ce95afe1b3a2e065",
            "version": "==2016.10"
        },
        "sendgrid": {
            "hash": "sha256:804cad97607c7885e302dd42754ddbee046567d1509020048e1d44d3c7024679",
            "version": "==3.6.3"
        },
        "python-dateutil": {
            "hash": "sha256:537bf2a8f8ce6f6862ad705cd68f9e405c0b5db014aa40fa29eab4335d4b1716",
            "version": "==2.6.0"
        },
        "twilio": {
            "hash": "sha256:746354f382f8fde3a04c313c90413ba22fe549664940949c7f6d5dafd350a5e1",
            "version": "==5.7.0"
        },
        "pillow": {
            "hash": "sha256:2498f309fdbae5282748e699d3b1358a2edbcf5ed5ed3383b8f3f2fa043abae2",
            "version": "==4.0.0"
        },
        "inflection": {
            "hash": "sha256:18ea7fb7a7d152853386523def08736aa8c32636b047ade55f7578c4edeb16ca",
            "version": "==0.3.1"
        },
        "httplib2": {
            "hash": "sha256:fe187f315336c3daa6616d09f327a6e6560b082fce59723f77336329fdcbfc36",
            "version": "==0.9.2"
        },
        "pilkit": {
            "hash": "sha256:e5c88386fa549d7d10f00ab96a4c69bf4128dcbfe477f8f4e077f69bffdad529",
            "version": "==1.1.13"
        },
        "opbeat": {
            "hash": "sha256:913ff244160cfa701fff3b8cc511462792c3e166d9fe5a01b542ad6afb090012",
            "version": "==3.5.2"
        },
        "djangorestframework-hstore": {
            "hash": "sha256:4825ae8aff299aa3dc5a137b8bd9ca3efe0580fcb5c3699eb7e1a1030b17465d",
            "version": "==1.3"
        },
        "six": {
            "hash": "sha256:0ff78c403d9bccf5a425a6d31a12aa6b47f1c21ca4dc2573a7e2f32a97335eb1",
            "version": "==1.10.0"
        },
        "django-taggit": {
            "hash": "sha256:8e6213c06f821cb16a69504baf01398d068db0b46adcb544d5d2ae2201d9eeea",
            "version": "==0.22.0"
        },
        "Faker": {
            "hash": "sha256:249d1bd8fddb80643d4dc91b72c6089c847ab2d0deead946a6d339209ac24146",
            "version": "==0.7.7"
        },
        "django-model-utils": {
            "hash": "sha256:92e2ea87147447935800cbc21d79ccf678298166e345c794340d6b0e7a3307e7",
            "version": "==2.6.1"
        },
        "djangorestframework-gis": {
            "hash": "sha256:0287c23a66d461f2b1b4a30cda80530301e594e8d6acfba7dfc86c815ba3d68e",
            "version": "==0.11"
        },
        "django-extensions": {
            "hash": "sha256:b79abdb0c9a0f6ba61701f299c7605830c4b2a8495d31461ac401d027bab2e10",
            "version": "==1.7.6"
        },
        "boltons": {
            "hash": "sha256:b2adaa9d5dcac9856c6940bb14f976018ed0affab968e1e2f94d92fb006c17b4",
            "version": "==17.0.0"
        },
        "urllib3": {
            "hash": "sha256:b64c0faa183e9e9e76193146c4147e82a734982c6b6719dca851d6cc4ec90c01",
            "version": "==1.20"
        },
        "django-push-notifications": {
            "hash": "sha256:a5b1b394d7bb9ea5b06775f731a1f896d234cd2bcef77559ede5def9b7217f39",
            "version": "==1.4.1"
        },
        "psycopg2": {
            "hash": "sha256:70490e12ed9c5c818ecd85d185d363335cc8a8cbf7212e3c185431c79ff8c05c",
            "version": "==2.6.2"
        },
        "django-hstore": {
            "hash": "sha256:85134043da56c4c4bd4c4e10a23b66f4ff84562e6d866b50125e35ba164cf459",
            "version": "==1.4.2"
        },
        "django-localflavor": {
            "hash": "sha256:f296544a784c7e88853421f348d1ccb01d7052985ba4fad8960ec735efab0493",
            "version": "==1.4.1"
        },
        "django-rest-auth": {
            "hash": "sha256:99a82f6eef524046d565d2198f998b740d37c9f629f9b231017a48215b22ce24",
            "version": "==0.8.2"
        },
        "django-appconf": {
            "hash": "sha256:ddab987d14b26731352c01ee69c090a4ebfc9141ed223bef039d79587f22acd9",
            "version": "==1.0.2"
        },
        "sendgrid-django": {
            "hash": "sha256:a92dbdbcec38992a9caf284f2aef1622a834488f158f66beb6213e28531e6743",
            "version": "==4.0.4"
        },
        "funcy": {
            "hash": "sha256:69c046b8fa07fe34fb6b7ef3b9dcd900f9527b39af35b81429de26003c3bc5fe",
            "version": "==1.7.2"
        },
        "certifi": {
            "hash": "sha256:f74a224a9860fd5a2e9757230a7ea3eba82d6d46914780abc18e70c8b58d4bf8",
            "version": "==2017.1.23"
        },
        "django-taggit-serializer": {
            "hash": "sha256:258fbf13354c00a19e00ea8c1829458e644be7b52cfd9cf39b90fe2ccf813ed5",
            "version": "==0.1.5"
        },
        "boto": {
            "hash": "sha256:e8da1ad3ce7f84aaa35ec68feeded0f55818232d676e03529877eb8e935a005a",
            "version": "==2.45.0"
        },
        "djangorestframework": {
            "hash": "sha256:f446041a944723e14502a0a5880d0bc74a499ac1075781177f2fa6d7fe7b415d",
            "version": "==3.5.3"
        },
        "django-crispy-forms": {
            "hash": "sha256:18e904c7bd55c45201739cb343272767ff820263a1fca40a7b388006ce94910c",
            "version": "==1.6.1"
        },
        "redis": {
            "hash": "sha256:97156b37d7cda4e7d8658be1148c983984e1a975090ba458cc7e244025191dbd",
            "version": "==2.10.5"
        },
        "factory-boy": {
            "hash": "sha256:246f7da9caf9bf855aaa73b4963353ccb147fdd3adcbc419fa29422c5b69dd4c",
            "version": "==2.8.1"
        },
        "requests": {
            "hash": "sha256:1a720e8862a41aa22e339373b526f508ef0c8988baf48b84d3fc891a8e237efb",
            "version": "==2.13.0"
        },
        "python-http-client": {
            "hash": "sha256:2e86716cdc68c28bf25fd64786246cb2d91a6803dd3a4e1028204f1e63ee90bc",
            "version": "==2.2.1"
        },
        "pysocks": {
            "hash": "sha256:02419a225ff5dcfc3c9695ef8fc9b4d8cc99658e650c6d4718d4c8f451e63f41",
            "version": "==1.6.6"
        },
        "python3-openid": {
            "hash": "sha256:915d9adcf77b7ae801e377c7732ab3208eaedc4fe99cb2b37f8155b076c6eb1e",
            "version": "==3.0.10"
        },
        "Django": {
            "hash": "sha256:4541a60834f28f308ee7b6e96400feca905fb0de473eb9dad6847e98a36d86d4",
            "version": "==1.10.5"
        },
        "olefile": {
            "hash": "sha256:61f2ca0cd0aa77279eb943c07f607438edf374096b66332fae1ee64a6f0f73ad",
            "version": "==0.44"
        }
    }
}
```

pipenv, version 3.2.11

Error:
```
An error occured while installing!
Double requirement given: Django==1.10.5 (from -r /tmp/tmp1jghxq4g-requirements.txt (line 49)) (already in django (from -r /tmp/tmp1jghxq4g-requirements.txt (line 3)), name='Django')
```

**Comment by kennethreitz** [comment] 2017-01-31 06:53
closing for #168

**Closed by kennethreitz** 2017-01-31 06:53 UTC
