### ISSUE TITLE
AttributeError on `pipenv --py` if no Pipfile is present

### ISSUE THREAD

**Issue by MrLeeh** [kennethreitz/pipenv#709] opened 2017-09-26 09:42 UTC
In my opinion this is a minor issue. If I type `pipenv --py` from within a directory where no Pipfile is present I get an AttributeError  complaining that self.pipfile_location is None and so doesn't provide a `split()` function. See the last lines of the Traceback:

    ...
    File "c:\python36\lib\site-packages\pipenv\project.py", line 99, in virtualenv_name
        sanitized = re.sub(r'[ $`!*@"\\\r\n\t]', '_', self.name)[0:42]
    File "c:\python36\lib\site-packages\pipenv\project.py", line 49, in name
        self._name = self.pipfile_location.split(os.sep)[-2]
    AttributeError: 'NoneType' object has no attribute 'split'

In my opinion it would be better to print a message like used for `pipenv --venv` which says: "No virtualenv has been created for this project yet!"

**Comment by nateprewitt** [comment] 2017-09-26 09:50
This looks like a duplicate of #643. What version of pipenv are you on @MrLeech? Could you please try upgrading if it's not 8.0.1.

**Comment by nateprewitt** [comment] 2017-09-26 09:51
Although this is a fundamental failure point on the name function which I think could probably have a better failure mode.

**Comment by MrLeeh** [comment] 2017-09-26 09:57
I have tried the latest version on PyPi (8.0.1) as well as the master branch of this Github repository. Both throw the same Error. I'm on Windows by the way, but I guess that shouldn't matter for this error.

**Closed** 2017-09-26 13:01 UTC

**Comment by MrLeeh** [comment] 2017-09-26 14:05
Thanks. Works now.

**Comment by kennethreitz** [comment] 2017-09-26 15:01
Sorry for the bug!
