### ISSUE TITLE
extras_require and length of name > 5 fails.

### ISSUE THREAD

**Issue by dfee** [kennethreitz/pipenv#870] opened 2017-10-10 07:01 UTC
I have a setup.py that looks like this:

```python3
from setuptools import setup, find_packages

setup(
    name='graphene_utils',
    version='1.0',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'graphene>=2.0.dev',
    ],
    extras_require={
        'sqlalchemy': [
            'sqlalchemy',
        ],
        'test': [
            'pylint',
        ],
    },
    entry_points='''
    [console_scripts]
    run=server:run
    ''',
)
```

When attempting `pipenv install "-e .[sqlalchemy]"` it fails with:
```bash
~/code/graphene_utils (virtualenvs/graphene_utils-Dw3J0BOS)
$ pipenv install "-e .[sqlalchemy]"
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Discovering imports from local codebase…
Installing -e .[sqlal…
⠸
Error:  An error occurred while installing -e .[sqlal!
.[sqlal should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
```

However, renaming the extra_requires to `sqla` works fine.

**Comment by nateprewitt** [comment] 2017-10-13 05:02
Yeah, this is definitely a bug. I haven't had a chance to look into it yet, but I'll try to set aside some time this weekend. If anyone else would like to pick this up before then, feel free.

**Comment by spott** [comment] 2017-10-23 22:57
Are there any workarounds for this?

**Comment by nateprewitt** [comment] 2017-10-23 22:58
We still haven't root caused the issue, so the only suggestion at this time is you'll have to use pip or a non-wheel (I wouldn't recommend with something like tensorflow).

**Comment by spott** [comment] 2017-10-23 22:59
What are the consequences of using pip inside `pipenv shell`?

Does this just screw with the lock file?

**Comment by nateprewitt** [comment] 2017-10-23 23:09
@spott yes, it will install but nothing will be added to the lockfile or Pipfile. This means you'd have to run this step on every install.

**Comment by spott** [comment] 2017-10-23 23:10
@nateprewitt: I'll have to run which step?  pipenv lock?

**Comment by nateprewitt** [comment] 2017-10-23 23:15
Tensorflow won't be added to the Pipfile when you install it via pip. This means it will also not be included in the lockfile when locking.

You'll need to run pipenv shell and install Tensorflow via pip anytime you run pipenv install.

**Comment by spott** [comment] 2017-10-23 23:16
@nateprewitt:  Ah.  Thanks.  hopefully this bug will be installed when I next need to do that.

**Comment by techalchemy** [comment] 2017-10-23 23:45
@nateprewitt I've got the bug and part of the solution (it's the same as the local file installation issues, relating to passing relative paths to the Requirements library which can't parse anything with slashes) -- basically converting to `file://` URI for the requirements library and then back to a relative path if it started as one for using in the pipfile.

The workaround is to pass a `file://` URI instead of a relative path, for now

**Closed** 2017-11-22 00:54 UTC
Labels: bug, help wanted
