### ISSUE TITLE
Foursquare lock error

### ISSUE THREAD

**Issue by singleton11** [kennethreitz/pipenv#213] opened 2017-02-08 14:38 UTC
```
➜  testpipenv pipenv install foursquare
Creating a Pipfile for this project...
Creating a virtualenv for this project...
⠋Running virtualenv with interpreter /home/singleton/.pyenv/versions/3.5.2/bin/python
Using base prefix '/home/singleton/.pyenv/versions/3.5.2'
New python executable in /home/singleton/Projects/testpipenv/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/singleton/Projects/testpipenv/.venv
Installing foursquare...
Collecting foursquare
Requirement already satisfied: six in ./.venv/lib/python3.5/site-packages (from foursquare)
Collecting requests>=2.1 (from foursquare)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Installing collected packages: requests, foursquare
Successfully installed foursquare-1!2016.9.12 requests-2.13.0

Adding foursquare to Pipfile's [packages]...
➜  testpipenv ls
Pipfile
➜  testpipenv vim Pipfile 
➜  testpipenv pipenv lock
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==3.3.6', 'console_scripts', 'pipenv')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 867, in lock
    do_lock()
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 431, in do_lock
    results = get_downloads_info(names_map, 'packages')
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 375, in get_downloads_info
    name = list(convert_deps_from_pip(names_map[fname]))[0]
KeyError: 'foursquare-1!2016.9.12.tar.gz'
➜  testpipenv 

```

**Comment by jacebrowning** [comment] 2017-02-08 16:00
I think this might be the same issue as https://github.com/kennethreitz/pipenv/issues/203.

**Comment by nateprewitt** [comment] 2017-02-08 16:05
Thanks @jacebrowning, it's similar but I'm trying to determine why we're failing at different points for each. I'm leaving this one open until it's confirmed they are both due to the version number.

**Comment by nateprewitt** [comment] 2017-02-08 16:21
Ok, this one is a bit odd. The `!` is being percent encoded to `%21` before being sent to us from pip. We then are trying to look up the unencoded name which is why we're encountering the key error. The immediate solution would be to un-percent-encode the package name before storing it, but I'm not sure if that will have negative effects on other packages at the moment.

I'd be happy if someone would like to look into this. Otherwise, I'm leaving this as low priority for the moment because this is the first case of non-alphanumeric characters in version numbers we've encountered thus far.

I'm leaving this open because it's distinct from #203.

**Comment by nateprewitt** [comment] 2017-02-08 16:27
As another note, this seems to be in direct conflict with versioning requirements laid out in [PEP 440](https://www.python.org/dev/peps/pep-0440), so I would consider this a problem with the source package rather than pipenv.

We can definitely be more tolerant of these kinds of things, but I'm not sure we can predict every possible version scheme someone can devise.

**Comment by nateprewitt** [comment] 2017-02-11 21:16
This should be resolved with #218.

**Closed by nateprewitt** 2017-02-11 21:16 UTC
Labels: bug

**Comment by jacebrowning** [comment] 2017-04-02 04:05
I am seeing a similar error running pipenv 3.5.4 on Windows (AppVeyor CI): https://ci.appveyor.com/project/jacebrowning/env-diff/build/1.0.18

```
Locking [dev-packages] dependencies...
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\pipenv\cli.py", line 863, in lock
    do_lock(no_hashes=no_hashes)
  File "c:\python27\lib\site-packages\pipenv\cli.py", line 423, in do_lock
    results = get_downloads_info(names_map, 'dev-packages')
  File "c:\python27\lib\site-packages\pipenv\cli.py", line 388, in get_downloads_info
    name = list(convert_deps_from_pip(names_map[fname]))[0]
KeyError: 'Jinja2-2.9.5-py2.py3-none-any.whl'
```

**Comment by nateprewitt** [comment] 2017-04-03 16:15
@jacebrowning, this seems like it may be specific to either Windows or Appveyor. I can't reproduce this in a linux environment which is making me think there may be something specific to how we're parsing filenames.

I'll need to either get an environment setup to test this, or I'll look into forking your repo and setting up my own instance of Appveyor for testing. If you feel like poking around, see if you can find the contents of `names_map` in this failure case, that would be really helpful.

**Comment by nateprewitt** [comment] 2017-04-24 20:58
@jacebrowning, you should find this fixed for appveyor in #326. We'll have that included in the next release within the next few days.

**Comment by jacebrowning** [comment] 2017-04-26 23:55
@nateprewitt Thanks for getting this out there! 3.6.0 works great on one of my AppVeyor builds (https://ci.appveyor.com/project/jacebrowning/template-python-demo/build/1.0.581) and has a new error in another (https://ci.appveyor.com/project/jacebrowning/env-diff/build/1.0.27):

```
Installing dependencies from Pipfile.lock...
An error occured while installing!
Traceback (most recent call last):
  File "C:\Python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\projects\env-diff\.venv\Scripts\pip.exe\__main__.py", line 9, in <module>
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\__init__.py", line 233, in main
    return command.main(cmd_args)
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\basecommand.py", line 252, in main
    pip_version_check(session)
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\utils\outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\utils\__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "c:\projects\env-diff\.venv\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'c:\\projects\\env-diff\\.venv\\lib\\site-packages\\colorama-0.3.8-py3.6.egg'
```

If I can determine the cause of this new failure, I'll submit an issue.

**Comment by nateprewitt** [comment] 2017-04-26 23:58
@jacebrowning this looks like it may be related to the Pip version you have installed in Appveyor. I'd make sure that's up to date and if that doesn't fix it, please open a new issue. Thanks!
