### ISSUE TITLE
Add something like NODE_ENV

### ISSUE THREAD

**Issue by sobolevn** [kennethreitz/pipenv#1115] opened 2017-11-23 10:06 UTC
Right now we only have a single way to install development environment: `pipenv install --dev`.

`npm` on the other hand has very useful [`$NODE_ENV`](https://github.com/npm/npm/issues/6803) variable. So it is possible to change the environment without changing the command itself: `npm install`.

Right now I have to do a conditional installation in my `Dockerfile`: `RUN pip install pipenv && test "$DJANGO_ENV" == production && pipenv install --system --deploy || pipenv install --dev --system --deploy`

I really think it should be simplified.

**Comment by erinxocon** [comment] 2017-11-23 16:57
@sobolevn Hi and thanks for using pipenv!  I think the use of that `NODE_ENV` variable ends up being more confusing for users when they are trying to get dependencies installed correctly, especially new users.  I think the explicit syntax of pipenv is more beneficial then nodes contextual varaible based commands.  `pipenv install` `pipenv install --dev` always give the same results regardless of the situation. We don't want to make any assumptions for the user, rather everything be explicit.  I'm going to close this as won't fix for now but thank you for your suggestion!

On another note: Could I get a look at your Pipfile?  Given the nature of your command with the `||` operator, it looks like its either install dependecies, or install dev dependecies, not one followed by the other as I would expect.  Do you have duplicate dependecies in your dev section that are also in your main section?  This is not how pipefile was intended to be used.

**Closed by erinxocon** 2017-11-23 16:57 UTC

**Comment by sobolevn** [comment] 2017-11-23 17:04
@erinxocon sure, https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/Pipfile

That's how I use `docker` containers. I use the same `Dockerfile` for both development and production. So, I specify my environment with `$DJANGO_ENV`. I either need only production dependencies or full dependencies (prod + dev) for testing and development. What am I doing wrong?

**Comment by techalchemy** [comment] 2017-11-23 17:12
@erinxocon @sobolevn `install --dev` still installs both development and default packages, so it seems fine

The use case makes sense but probably overcomplicates things a bit

**Comment by erinxocon** [comment] 2017-11-23 17:18
@techalchemy yeah I forgot that --dev installs all including dev oopps!  I still don't think we should use an env variable to decide on what the functionality of the raw `install` command, I would rather the user be explicit about what they want.  

@sobolevn You aren't doing anything wrong in your dockerfile, I had a misunderstanding on how that docker command works.

**Comment by techalchemy** [comment] 2017-11-23 17:24
@erinxocon yeah I think it's been changed everywhere else... lol

but I also kinda feel like this might be the one place where it makes sense as it is? I can't imagine someone only wanting their dev dependencies

**Comment by erinxocon** [comment] 2017-11-23 17:27
@techalchemy Yes, I agree, in order to use the dev deps, you have to have had other dependencies.  Otherwise the user would have dups in their Pipfile in the two different sections.
