### ISSUE TITLE
pipenv cannot install matplotlib==2.1.0, but can do 2.1.0rc1

### ISSUE THREAD

**Issue by mwillsey** [kennethreitz/pipenv#861] opened 2017-10-08 23:03 UTC
I haven't looked into what's happening with matplotlib 2.1.0, but trying to install it with pipenv fails with:
`pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/0l/c9dt_3f11ks8_r84qtrjj0k00000gn/T/tmp7qdfg9tlbuild/subprocess32/`

My system is pretty clean. pipenv is installed by pipsi and is up-to-date.
```sh
$ pip3 list
pip (9.0.1)
setuptools (36.5.0)
virtualenv (15.1.0)
wheel (0.30.0)
$ pipenv --version
pipenv, version 8.2.6
```

Here's how to reproduce.
```sh
mkdir dummy
cd dummy

# this fails
pipenv install "matplotlib==2.1.0"

# this works
pipenv install "matplotlib==2.1.0rc1"
```

Thanks!

**Comment by vphilippon** [comment] 2017-10-13 18:06
That's a bug fixed in 8.2.7. Make sure to clear your cache after upgrading (`pipenv lock --clear`)
(Was fetching `subprocess32`, which is a Py2 dependency, even on Py3.)

**Comment by erinxocon** [comment] 2017-10-18 04:37
I can confirm this is fixed in the latest release!  Closing!

**Closed by erinxocon** 2017-10-18 04:37 UTC

**Comment by cmlccie** [comment] 2017-12-05 02:32
I ran into this issue on my machine using pipenv, version 8.3.2.  To verify that it wasn't something in my environment, I have replicated it on a clean-build VM of macOS High Sierra 10.13.1 (17B1003).

**Environment:**
* macOS High Sierra 10.13.1
* Python Interpreters:
  * `python` Python 2.7.10 (system)
  * `python2` Python 2.7.14 (installed via pyenv)
  * `python3` Python 3.6.3 (installed via pyenv)
* pipenv, version 8.3.2 (installed via homebrew)


**Steps to Reproduce:**
``` bash
$ mkdir -p ~/dev/projects/pipenv-matplotlib
$ cd ~/dev/projects/pipenv-matplotlib
$ pipenv install --three --verbose matplotlib
```

**Output:**  _(verbose output attached)_
``` bash
Chriss-Mac:pipenv-matplotlib cmlccie$ pipenv install --three --verbose matplotlib > verbose.log
Creating a virtualenv for this project…
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/Users/cmlccie/.pyenv/versions/3.6.3'
New python executable in /Users/cmlccie/.local/share/virtualenvs/pipenv-matplotlib-XtkrZ9f3/bin/python3
Also creating executable in /Users/cmlccie/.local/share/virtualenvs/pipenv-matplotlib-XtkrZ9f3/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/cmlccie/.local/share/virtualenvs/pipenv-matplotlib-XtkrZ9f3
Creating a Pipfile for this project…
Installing u'matplotlib'
$ "/Users/cmlccie/.local/share/virtualenvs/pipenv-matplotlib-XtkrZ9f3/bin/pip" install   --verbose   "matplotlib" -i https://pypi.python.org/simple --exists-action w
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/cli.py", line 1935, in install
    do_lock(system=system, pre=pre)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/cli.py", line 1121, in do_lock
    pre=pre
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/utils.py", line 461, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 296, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/sh/5sddjf85009d0585hwjxd3cr0000gn/T/tmpRZW5Ttbuild/subprocess32/
Chriss-Mac:pipenv-matplotlib cmlccie$ 
```
[verbose.log](https://github.com/kennethreitz/pipenv/files/1529506/verbose.log)

**Comment by vphilippon** [comment] 2017-12-05 14:41
@cmlccie Thanks for the report. By looking at the log, I can tell that this is not the same root cause.
To help with tracking, please open a new issue, and specify in the title that it was "installed via homebrew".
Also, tag me in that new issue.
Thanks!

**Comment by drizzersilverberg** [comment] 2017-12-31 17:33
I have this error in latest pipenv version:

`
dendi@drizzer:~/git/github/test$ pipenv --version
pipenv, version 9.0.1

dendi@drizzer:~/git/github/test$ pipenv --python 3.6
Creating a virtualenv for this project…
Using /usr/bin/python3.6m to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python3.6m
Using base prefix '/usr'
New python executable in /home/dendi/.local/share/virtualenvs/test-YOjpHLSw/bin/python3.6m
Also creating executable in /home/dendi/.local/share/virtualenvs/test-YOjpHLSw/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/dendi/.local/share/virtualenvs/test-YOjpHLSw
Creating a Pipfile for this project…

dendi@drizzer:~/git/github/test$ pipenv install matplotlib
Installing matplotlib…
Collecting matplotlib
  Using cached matplotlib-2.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy>=1.7.1 (from matplotlib)
  Using cached numpy-1.13.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting pytz (from matplotlib)
  Using cached pytz-2017.3-py2.py3-none-any.whl
Collecting python-dateutil>=2.0 (from matplotlib)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib)
  Using cached six-1.11.0-py2.py3-none-any.whl
Installing collected packages: numpy, six, cycler, pyparsing, pytz, python-dateutil, matplotlib
Successfully installed cycler-0.10.0 matplotlib-2.1.1 numpy-1.13.3 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.3 six-1.11.0

Adding matplotlib to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==9.0.1', 'console_scripts', 'pipenv')()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 1934, in install
    do_lock(system=system, pre=pre)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 1102, in do_lock
    pre=pre
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 545, in resolve_deps
    resolved_tree = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 507, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 296, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp2EKxYNbuild/subprocess32/
dendi@drizzer:~/git/github/test$
`
