### ISSUE TITLE
Add an option to `lock -r` only production dependencies

### ISSUE THREAD

**Issue by iamale** [kennethreitz/pipenv#260] opened 2017-03-10 20:36 UTC
For example, to generate `requirements.txt` for legacy deployments. Of course, installing all the development dependencies is an option, but it can be hard (i. e. [Fabric](https://pypi.python.org/pypi/Fabric3) depends on [cryptography](https://pypi.python.org/pypi/cryptography) which needs some C headers installed, but we don't need Fabric on the server in first place).

This can be tricky, though, depending on how we generate the current `pipenv lock -r` output.

**Comment by iamale** [comment] 2017-03-10 20:53
I'm currently using this, but it seems like a bit of a hack:

```py
with open("requirements.txt", "w") as req:
    req.write("# This file is generaged on deploy - do not modify\n\n")
    operations.local("pipenv lock")
    lock = json.load(open("Pipfile.lock"))
    for name, dep in lock["default"].items():
        req.write("{name}{version} --hash={hash}\n".format(
            name=name,
            version=dep["version"],
            hash=dep["hash"]))
```

**Comment by nateprewitt** [comment] 2017-03-10 21:59
Hey @iamale, thanks for taking the time to open this issue. It happens to be a duplicate of #245 where Kenneth decided we won't currently be supporting requirements.txt with a differentiation between dev dependencies.

You'll find a comment [here](https://github.com/kennethreitz/pipenv/issues/245#issuecomment-283694215) in that issue which notes a slightly simpler script using Pipenv to create a simplified `requirements.txt`. This will accomplish what you're currently trying to do.

**Closed by nateprewitt** 2017-03-10 21:59 UTC
