### ISSUE TITLE
pipenv cannot install pyautogui module, but pip can

### ISSUE THREAD

**Issue by beastwork** [kennethreitz/pipenv#667] opened 2017-09-23 12:09 UTC
I tried to install pyautogui in Python 3.6 using "pipenv install" and received the below error message.  I proceeded to enter the bash shell, and used pip3 to install the module to my virtualenv without issue.  I'm not sure why pip would work and pipenv wouldn't.

"pipenv run pip3 install pyautogui"    installs the module as well.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==7.6.3', 'console_scripts', 'pipenv')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/cli.py", line 1682, in install
    do_lock(system=system, pre=pre)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/cli.py", line 1044, in do_lock
    pre=pre
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/utils.py", line 468, in resolve_deps
    resolved_tree.update(resolver.resolve())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/piptools/resolver.py", line 107, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/piptools/resolver.py", line 195, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/piptools/resolver.py", line 274, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/piptools/repositories/pypi.py", line 145, in get_dependencies
    self._dependencies_cache[ireq] = reqset._prepare_file(self.finder, ireq)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/patched/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/2c/yc22p1pn5f1_s45vw6czf_l80000gn/T/tmpebjrqo_ybuild/pyautogui/
```

**Comment by kennethreitz** [comment] 2017-09-23 14:36
the problem isn't with installing, it's with locking. that package probably has a wonky setup.py file that can't be run on your version of python.

**Comment by beastwork** [comment] 2017-09-23 15:03
I'm not sure I understand your explanation.  If I install the package to the virtual environment with pip I don't have any issues.  The issue only occurs when using the pipenv install command.  This is all on the same version of python which doesn't jive with your response.

**Comment by kennethreitz** [comment] 2017-09-23 16:04
The issue is hard to explain, but pip-tools is running 'setup.py egg_info' against your dependency, which is likely using a different version of python (the one you installed pipenv with) than the one you're using in your virtualenv). 

This is causing your `setup.py egg_info` call to fail, because this package has a poorly written `setup.py` file that either isn't compatible with 2/3 or has some other weirdness going on.

**Comment by kennethreitz** [comment] 2017-09-23 16:05
this is out biggest standing issue, and i'm not sure there's anything we can do about it.

**Comment by kennethreitz** [comment] 2017-09-23 16:06
The issue isn't with installing... it's with locking. e.g., resolving the dependency graph, afterwards.

You can always do `pipenv install --skip-lock` to have this succeed.

**Comment by kennethreitz** [comment] 2017-09-23 16:06
It's the generating the lockfile part that is choking.

**Comment by kennethreitz** [comment] 2017-09-23 16:06
I'll see if I can get it to ignore installed.

**Comment by kennethreitz** [comment] 2017-09-23 16:08
Try `pipenv lock --clear` and tell me if that's successful. 

If it is, I'll make it default.

**Comment by kennethreitz** [comment] 2017-09-23 16:13
`pipenv lock --clear` does not appear to fix this issue. I will try to dig in farther.

**Comment by kennethreitz** [comment] 2017-09-23 16:13
Basically, this package is poorly packaged. That's the problem.

**Comment by kennethreitz** [comment] 2017-09-23 16:14
`python setup.py egg_info` should work for any dependency, but it does not work for this, because it errors out.

**Comment by kennethreitz** [comment] 2017-09-23 16:14
so, this package is incompatible with pipenv's locking functionality, unfortunately.

**Comment by kennethreitz** [comment] 2017-09-23 16:14
and i don't think there's anything we can do about it.

**Closed** 2017-09-23 16:16 UTC

**Comment by AlJohri** [comment] 2017-09-23 17:03
@beastwork The issue is with with how pyautogui deals with its `version`: https://github.com/asweigart/pyautogui/blob/master/setup.py

```
version=__import__('pyautogui').__version__
```

hardcoding to `version='0.9.36'` fixes the issue.

if you care enough, this should be a trivial PR to make against pyautogui. The setup.py shouldn't try to import itself. As an example, you can see how requests organizes their metadata here: https://github.com/requests/requests/blob/master/requests/__version__.py

**Comment by kennethreitz** [comment] 2017-09-23 19:19
see a good setup.py example here: https://github.com/kennethreitz/setup.py

**Comment by beastwork** [comment] 2017-09-23 23:16
@AlJohri I was unable to reproduce your results.  As an alternative I'll just use pip to create a requirements file.  Thanks for the feedback.
