### ISSUE TITLE
Pipfile.lock from pipenv lock missing hash

### ISSUE THREAD

**Issue by jamessha** [kennethreitz/pipenv#270] opened 2017-03-13 23:01 UTC
I have a Pipfile that looks like
`[packages]
jupyter = "==1.0.0"
numpy = "==1.12.0"
pandas = "==0.19.2"
requests = "==2.13.0"
scikit-learn = "==0.18.1"
scipy = "==0.18.1"
alembic = "==0.8.10"
psycopg2 = "==2.6.2"
python-gflags = "==3.1.1"
nose2 = "==0.6.5"
h5py = "==2.6.0"
pydotplus = "==2.0.2"
tensorflow-gpu = "==1.0.1"
hyperopt = "==0.1"
lime = "==0.1.1.19"
SQLAlchemy = "==1.1.5"
Keras = "==1.2.2"

[requires]
python_version = "3.5"`

pipenv lock outputs a Pipefile.lock that looks like
`...
"future": {
            "hash": "sha256:e39ced1ab767b5936646cedba8bcce58239
8233d6a627067d4c6a454c90cfedb",
            "version": "==0.16.0"
        },
        "h5py": "==2.6.0",
        "html5lib": {
            "hash": "sha256:b8934484cf22f1db684c0fae27569a0db40
4d0208d20163fbf51cc537245d008",
            "version": "==0.999999999"
        },
...
`

which looks like it's missing the hash for h5py. However a hash for 2.6.0 seems to exist hash=sha256:cbb004160ddcfa5d75bc3f8894dbfe453
7913941fcba126c40e91be92a2fcf5a. I can workaround by manually adding the hash, however is this expected behavior?

Thanks!

**Comment by nateprewitt** [comment] 2017-03-13 23:10
Hey @jamessha, this is not expected behavior. I'm not at a computer right now, so I can't do any deep diving until later this evening. Could you confirm for me you're using pipenv 3.5.3? If you aren't, would you please upgrade and verify this problem still exists on the latest version on pipenv? Thanks!

**Comment by jamessha** [comment] 2017-03-13 23:36
Yes, 
`pipenv --version
pipenv, version 3.5.3`

**Comment by jamessha** [comment] 2017-03-14 00:15
I noticed that for packages this occurs there's a more recent version of the package of the same version but with "-1" appended, eg h5py-2.6.0-1 or matplotlib-2.0.0-1. I don't know enough about python package versioning to know what -1 means but pipenv seems to create hashes for these versions when a version isn't specified.

**Comment by nateprewitt** [comment] 2017-03-14 00:34
Hmm, so I actually can't reproduce this. I've tried Python 3.5 on both mac OS Sierra and Ubuntu 14.04 without an issue. Given the hash you provided it seems you're on linux, which distro are you using? I can't find a reason this wouldn't work in the codebase.

When you perform `pip install h5py==2.6.0` everything installs fine?

**Comment by jamessha** [comment] 2017-03-14 00:48
I'm on Ubuntu 14.04.

Ah, pipenv seems to do the right then when I install with
`pipenv  install h5py==2.6.0`
then
`pipenv lock`

However if I first install with
`pipenv install h5py`
then manually edit the Pipfile to require 2.6.0 then lock, I get this. 

If I don't do the manual edit then lock, the Pipfile.lock will read
"h5py": {
            "hash": "sha256:734256858b3fd5fcad92f20f8d7e4da5a93fd011dfe5624f89e12f884227bea1",
            "version": "==2.6.0-1"
        },
and pipenv install will error out with 
`Could not find a version that satisfies the requirement h5py==2.6.0-1 (from -r /tmp/tmp21kom305-requirements.txt (line 1)) (from versions: 2.2.1, 2.3.0b1, 2.3.0, 2.3.1, 2.4.0b1, 2.4.0, 2.5.0, 2.6.0, 2.7.0rc2)
No matching distribution found for h5py==2.6.0-1 (from -r /tmp/tmp21kom305-requirements.txt (line 1))`

**Comment by nateprewitt** [comment] 2017-03-14 16:13
So, they definitely have an (implicit post release)[https://www.python.org/dev/peps/pep-0440/#implicit-post-releases] on PyPI, so 2.6.0-1 is the latest "2.6.0" release. We've made changes in the past to be able to handle these, but the actual expected behaviour from pip is unclear to me.

@kennethreitz do you have any background here, or someone we could tag in to answer this question. `h5py` has multiple files tagged with either `2.6.0` or `2.6.0-1` all under the same `2.6.0` release.

**Comment by nateprewitt** [comment] 2017-03-14 18:03
So a bit of experimenting leads me to believe we should actually be ignoring the post-release info in the version number. I am almost certain though that we patched this issue specifically because people were having problems with the version numbers after a `-` being dropped. I can't seem to find the exact reference though because there were several issues early on about version problems.

I'd like to get some more insight from someone more familiar with PEP440 and the pypa infrastructure. We'll leave this open as a possible bug for now.

**Comment by kennethreitz** [comment] 2017-03-21 16:43
sounds like we need to write a test for this!

**Comment by nateprewitt** [comment] 2017-03-21 17:16
So we have a test for this but the test *may* be wrong.  I think we need confirmation from someone like Donald that implicit post release numbers should be ignored in all cases with pip. If that's the case we'll need to slightly rework how we deal with dashes in version numbers.

**Comment by kennethreitz** [comment] 2017-03-24 16:52
@dstufft any input here?

**Comment by nateprewitt** [comment] 2017-03-24 16:58
@dstufft just to save you reading time, the simple example is if a release `1.0` is put up on PyPI and then someone does a post-release as `1.0-1`. Does `pip` expect `pip install project==1.0-1` or is that handled on the backend so `pip install project==1.0` is still the expected command? I'm under the impression it's the latter but wanted to verify that we're not regressing anything.

**Comment by nateprewitt** [comment] 2017-04-23 14:31
This should be resolved with #314. @jamessha feel free to test this out on the master branch or it will be included in the next release. Thanks again for bringing this to our attention!

**Closed by nateprewitt** 2017-04-23 14:31 UTC
Labels: reported bug
