### ISSUE TITLE
Can't find correct package having name as multiple dashed

### ISSUE THREAD

**Issue by jeyraof** [kennethreitz/pipenv#232] opened 2017-02-17 06:56 UTC
When i install `django-debug-toolbar` using pipenv install, it installed `django-debug` package.
But if i tried to uninstall `django-debug-toolbar` after installed it using pip directly, it work correctly.

please check this :D

Install:
```bash
❯ pipenv install django-debug-toolbar
Installing django-debug...
Collecting django-debug
Installing collected packages: django-debug
Successfully installed django-debug-0.1.1

Adding django-debug to Pipfile's [packages]...
```

Uninstall:
```bash
❯ pipenv uninstall django-debug-toolbar
Un-installing django-debug-toolbar...
Uninstalling django-debug-toolbar-1.6:
  Successfully uninstalled django-debug-toolbar-1.6

Removing django-debug-toolbar from Pipfile...
```

**Comment by nateprewitt** [comment] 2017-02-17 14:41
@jeyraof, can you confirm for me that you're using the latest version of pipenv (3.4.1)? I am currently unable to reproduce this locally.

**Comment by nateprewitt** [comment] 2017-02-19 15:24
Closing due to lack of information and inability to reproduce. Please feel free to reopen if you are still experiencing this on the current pipenv.

**Closed by nateprewitt** 2017-02-19 15:24 UTC
Labels: needs more information

**Comment by jeyraof** [comment] 2017-02-20 03:03
@nateprewitt Thanks. After upgrade pipenv version, it works well
