### ISSUE TITLE
--system argument seems to have gone away

### ISSUE THREAD

**Issue by gregplaysguitar** [kennethreitz/pipenv#384] opened 2017-05-29 19:58 UTC
To reproduce:

    pip install pipenv
    pipenv --version
    > pipenv, version 4.1.1
    pipenv --system install six
    > Error: no such option: --system

I've tried this on macOS and Ubuntu.

**Comment by nateprewitt** [comment] 2017-05-29 20:10
Thanks for moving this into a new issue @gregplaysguitar 😊. So this has to do with argument ordering. For some reason that I still have yet to pindown, `click` specifies `[OPTIONS]` before `COMMAND` in the usage statement. We manually patched this for `--two/--three` but it clearly affects every OPTION passed to pipenv. I'll leave this open for now to track the issue further.

In the meantime, the syntax you're actually looking for is `pipenv install --system six`.

**Comment by gregplaysguitar** [comment] 2017-05-29 21:26
Ah... got it. Thanks for the explanation. I actually tried that, but the thing that threw me was that the first thing it does is creates a virtualenv, even though I'm installing to system. So when I do this from my home directory:

    pipenv --system install six
   
It first creates a virtualenv at `/Users/greg/.local/share/virtualenvs/greg-Tm8LTBrB`, but then installs six to the system at `/usr/local/lib/python3.5/site-packages`

Is this the intended behaviour?

**Comment by nateprewitt** [comment] 2017-05-30 14:07
@gregplaysguitar, yes and no. We currently have code that verifies the Pipfile and Virtualenv are intact before installing. When you're installing from your home directory, are you expecting the Pipfile  there to be populated with each install?

**Comment by kennethreitz** [comment] 2017-05-30 15:08
That is currently the intended behavior, but there is room for improvement :)

**Comment by gregplaysguitar** [comment] 2017-05-30 19:13
Ok, thanks - now I understand what's going on a lot better!

> When you're installing from your home directory, are you expecting the Pipfile there to be populated with each install?

I'm not, that example was a bit contrived - what I'm actually doing is using pipenv to build an environment based on an existing Pipfile. 

What I really need is a tool that takes a Pipfile and installs into an arbitrary environment, be it an active virtualenv, or the system or whatever. I'm not sure this is the intended purpose of pipenv? It is working though, the redundant virtualenv doesn't do any harm, apart from the possible confusion.

**Comment by gregplaysguitar** [comment] 2017-05-30 19:22
This is actually a repeat of the discussion from #289 now so we should probably close this issue and head back over there, since `--system` is accounted for?

**Comment by nateprewitt** [comment] 2017-05-30 19:47
Yeah, I think that's alright @gregplaysguitar. We'll close this out in favor of #289 if that's more in line with what you're looking for.

**Closed by nateprewitt** 2017-05-30 19:47 UTC
