### ISSUE TITLE
The "pipenv update" command  does not work anymore on windows (pipenv 8.1.4, python 3.6.2 Windows 8.1)

### ISSUE THREAD

**Issue by pvergain** [kennethreitz/pipenv#744] opened 2017-09-28 06:24 UTC
C:\Tmp>mkdir test_update

C:\Tmp>cd test_update\

C:\Tmp\test_update>pipenv --version
pipenv, version 8.1.4

C:\Tmp\test_update>pipenv install requests
Creating a virtualenv for this project…
Using base prefix 'c:\\python36'
New python executable in c:\project\python_envs\test_update-PCkJl9he\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location: c:\project\python_envs\test_update-PCkJl9he
Creating a Pipfile for this project…
Installing requests…
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Using cached idna-2.6-py2.py3-none-any.whl
Installing collected packages: certifi, urllib3, chardet, idna, requests
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22

Adding requests to Pipfile's [packages]…
P.S. You have excellent taste!
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock!

C:\Tmp\test_update>pipenv update
Updating all dependencies from Pipfile…
Found 5 installed package(s), purging…
Uninstalling certifi-2017.7.27.1:
  Successfully uninstalled certifi-2017.7.27.1
Uninstalling chardet-3.0.4:
  Successfully uninstalled chardet-3.0.4
Uninstalling idna-2.6:
  Successfully uninstalled idna-2.6
Uninstalling requests-2.18.4:
  Successfully uninstalled requests-2.18.4
Uninstalling urllib3-1.22:
  Successfully uninstalled urllib3-1.22

Environment now purged and fresh!
Installing dependencies from Pipfile.lock…
Traceback (most recent call last): 0/5 — 00:00:00
  File "C:\Python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\.local\bin\pipenv.exe\__main__.py", line 9, in <module>
  File "c:\.local\venvs\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\.local\venvs\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\.local\venvs\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\.local\venvs\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\.local\venvs\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\.local\venvs\pipenv\lib\site-packages\pipenv\cli.py", line 2385, in update
    do_init(dev=dev, verbose=verbose)
  File "c:\.local\venvs\pipenv\lib\site-packages\pipenv\cli.py", line 1253, in do_init
    skip_lock=skip_lock, verbose=verbose, concurrent=concurrent)
  File "c:\.local\venvs\pipenv\lib\site-packages\pipenv\cli.py", line 803, in do_install_dependencies
    index=index
  File "c:\.local\venvs\pipenv\lib\site-packages\pipenv\cli.py", line 1333, in pip_install
    c = delegator.run(pip_command, block=block)
  File "c:\.local\venvs\pipenv\lib\site-packages\pipenv\vendor\delegator.py", line 257, in run
    c.run(block=block, binary=binary)
  File "c:\.local\venvs\pipenv\lib\site-packages\pipenv\vendor\delegator.py", line 149, in run
    s = PopenSpawn(self._popen_args, **pexpect_kwargs)
  File "c:\.local\venvs\pipenv\lib\site-packages\pipenv\vendor\pexpect\popen_spawn.py", line 45, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "C:\Python36\Lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\Lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
  ================================ 0/5 — 00:00:00

C:\Tmp\test_update>

C:\Tmp\test_update>pipenv run python --version
Python 3.6.2

**Comment by nateprewitt** [comment] 2017-09-28 09:48
Thanks for reporting this @pvergain. It looks like this is happening on our Appveyor instance as well. I haven't had a chance to look at the recent changes since yesterday to pin point the cause of the error but we'll take a look ASAP.

**Comment by nateprewitt** [comment] 2017-09-28 11:38
So just for further debugging info, this is the command we're executing on appveyor that's blowing up but I'm still not sure the root cause. I don't immediately see any changes between when the build worked and stopped working that should affect this.

```
$ "C:\Python27-x64\Scripts\pip.exe" install   --verbose   -r c:\users\appveyor\appdata\local\temp\1\pipenv-7owu2_-requirement.txt -i https://pypi.python.org/simple --exists-action w
```

**Comment by nateprewitt** [comment] 2017-09-28 12:04
Ok, it's definitely related to the quoting of the pip path. The last working commit we have only has the quotes removed and works as expected. We'll need to find an alternative for paths with spaces on Windows.

```$ C:\Python27-x64\Scripts\pip.exe install     -r c:\users\appveyor\appdata\local\temp\1\pipenv-dbn3v6-requirement.txt -i https://pypi.python.org/simple --exists-action w```

**Comment by rob356** [comment] 2017-09-28 13:01
I ran into this same issue myself and just got a PR merged into pexpect that fixes this issue: https://github.com/pexpect/pexpect/pull/447. With this you can keep the quoted paths.

**Comment by nateprewitt** [comment] 2017-09-28 13:24
Thanks so much for taking care of that @rob356! I've updated our vendored pexcept with your patch and once the build runs green, we'll merge it.

**Comment by kennethreitz** [comment] 2017-09-28 13:29
should be fixed in master

**Closed** 2017-09-28 13:30 UTC
Labels: bug

**Comment by kennethreitz** [comment] 2017-09-28 13:44
8.1.5 released
