### ISSUE TITLE
For some reason - pipenv sometimes ignores versions when generating lock.

### ISSUE THREAD

**Issue by beregond** [kennethreitz/pipenv#271] opened 2017-03-13 23:41 UTC
![screenshot from 2017-03-14 00-20-32](https://cloud.githubusercontent.com/assets/956019/23879617/7bef433a-084e-11e7-97d2-b986b1bbd37b.png)

Note the difference between Django 1.10.4 I installed and Django1.10.6 which is found in lock file.

Some extra debug info:

![screenshot from 2017-03-14 00-40-09](https://cloud.githubusercontent.com/assets/956019/23879681/d3a76062-084e-11e7-8c43-92d14f0e3858.png)

Also important to note - when I try this in docker (`docker run -it python:3.6 bash`) - then everything works as expected.

**Comment by nateprewitt** [comment] 2017-03-14 00:43
This is kind of an odd one. pip doesn't provide a guarantee avoiding version conflicts currently but a single pinned version like this should definitely not be changing. I can't reproduce this locally unfortunately. Could you provide the python version you're using (`pipenv run python --version`)?

Also could you provide the output of `pipenv run pip freeze` and `pipenv --where` for me? Thanks!

**Comment by nateprewitt** [comment] 2017-03-14 16:16
I'm fairly confident this is directly related to the problem addressed in #272. I've pushed a patch to master and will try to get a release out shortly. If you are still experiencing this on pipenv 3.5.4, please feel free to reopen this and we can dig further.

Thanks again @beregond!

**Closed by nateprewitt** 2017-03-14 16:16 UTC

**Comment by beregond** [comment] 2017-03-25 00:20
I've shreded those pipenvs earlier, but anyway maybe this will be useful somehow for you:

![screenshot from 2017-03-25 01-19-59](https://cloud.githubusercontent.com/assets/956019/24317617/3d13619c-10f9-11e7-8c41-47e5cf929532.png)

> If you are still experiencing this on pipenv 3.5.4, please feel free to reopen this and we can dig further.

Okay, thanks for help :)
